apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../klipper/app.yaml
  - ../mainsail/app.yaml
  - ../orcaslicer/app.yaml
  - ../spoolman/app.yaml
  - ../ustreamer/app.yaml