apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: bazarr
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          image: linuxserver/bazarr:1.5.6
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 6767
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: media
          persistentVolumeClaim:
            claimName: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
spec:
  selector:
    app: bazarr
  ports:
    - port: 6767
      targetPort: 6767
      protocol: TCP
      name: http
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bazarr
  namespace: media
spec:
  secretName: bazarr.saturn.ci
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - bazarr.saturn.ci
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Bazarr
    gethomepage.dev/group: Servarr
    gethomepage.dev/icon: bazarr
    gethomepage.dev/weight: 16
    gethomepage.dev/widget.type: bazarr
    gethomepage.dev/widget.url: http://bazarr.media.svc.cluster.local:6767
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: 'traefik-forwardauth-authelia@kubernetescrd'
    external-dns.alpha.kubernetes.io/enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: bazarr.saturn.ci
    external-dns.alpha.kubernetes.io/target: direct.saturn.ci
spec:
  tls:
    - secretName: bazarr.saturn.ci
      hosts:
        - bazarr.saturn.ci
  rules:
    - host: "bazarr.saturn.ci"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: bazarr
                port:
                  number: 6767