apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanuparr
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cleanuparr
  template:
    metadata:
      labels:
        app: cleanuparr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: cleanuparr
          image: linuxserver/cleanuparr:1.5.6
          env:
            - name: PORT
              value: "11011"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 11011
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: cleanuparr-config
        - name: media
          persistentVolumeClaim:
            claimName: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuparr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cleanuparr
  namespace: media
spec:
  selector:
    app: cleanuparr
  ports:
    - port: 11011
      targetPort: 11011
      protocol: TCP
      name: http
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cleanuparr
  namespace: media
spec:
  secretName: cleanuparr.saturn.ong-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - cleanuparr.saturn.ong
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cleanuparr
  namespace: media
  annotations:
    "kubernetes.io/ingress.class": traefik
    "traefik.ingress.kubernetes.io/router.tls": "true"
    "external-dns.alpha.kubernetes.io/hostname": cleanuparr.saturn.ong
    "external-dns.alpha.kubernetes.io/target": direct.saturn.ong
spec:
  tls:
    - secretName: cleanuparr.saturn.ong-tls
  rules:
    - host: "cleanuparr.saturn.ong"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: cleanuparr
                port:
                  number: 11011