apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smb-helm
  namespace: argocd
spec:
  project: default

  source:
    chart: csi-driver-smb
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    targetRevision: 1.20.3
    helm:
      releaseName: smb

  destination:
    name: in-cluster
    namespace: smb

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
    automated:
      prune: true
      selfHeal: true

  