apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas
  namespace: external
spec:
  secretName: truenas.saturn.ci
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - truenas.saturn.ci