apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: coral-tpu
  namespace: node-feature-discovery
spec:
  rules:
    - name: coral-tpu
      labels:
        "feature.node.kubernetes.io/coral-tpu": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: {op: In, value: ["1ac1"]}
            class: {op: In, value: ["809a"]}