apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSRecord
metadata:
  name: saturn.ci-mx
  namespace: external
spec:
  endpoint:
    dnsName: saturn.ci
    providerSpecific:
      - name: external-dns.kubernetes.io/cloudflare-proxied
        value: "false"
    recordType: MX
    targets:
      - "10 mail.saturn.ci"