apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: printer-ustreamer
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: master
    path: kubernetes/home/printer/ustreamer

  destination:
    server: in-cluster
    namespace: printer

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  plugin: {}