apiVersion: v1
kind: Secret
metadata:
    name: backup-credential
    namespace: longhorn-system
type: Opaque
stringData:
    CIFS_USERNAME: ENC[AES256_GCM,data:lJ0ygJ/2udHtCRM=,iv:jRECNyD54kqyHCsbaw6fupW80DSQZ+yrOPrzLLGXc20=,tag:gSt0oOCzOQLW4gJwkWGfFA==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:pO3kYtjUwlY+Th0zIw71HaXxkx0=,iv:SHJcnM+ljwUR6ri4dxlwqkX1XXfzXe4bZWVPzwENgvw=,tag:evIor9EPMU+zNXi18W9pzw==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQjFpZHRneXBFalpSUXRC
            Z1ptclNXajQyem1xVDZGdVhhMFdJbVpucFFZCkRWK2JQYlI0TGxWK2k5ZUplZEhC
            WXVCNDdzZjRiaXBjOFhPVXVldHF6NjQKLS0tIDZxOHBrVm9lT1ZpQlZXQ0k1NG82
            ZktvVTJpUnQ1UVJUYWtObm9iYzFFQlkKyDLBDx4detamGCkIGnoRn5ixK0RZcGhG
            FnXzDPZbtpb0sEZRtJaziqE+Z73JSd00/TH7JyHJYoATJByxt+eycg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRXdtWEJQOGoyREdyRXlR
            Sm91SENHNTJEYnhOdVRjMzlPd3NVRW9lWjBFCks3clkvem1rTDZZM3BONFNuR0FR
            SGFoVGsvQ0ZRSUR6cVZoZnFxNFZpUWcKLS0tIDdocjR0b0RndWpkMVM0RVZ0MTJF
            MlpYQWY4UXNFRmZVQW9rMzlRRmtIWWMKHUSKBuCB/fv/eXNa7aCZqDoOUs+VrFut
            BGfKPZJDCCFhlG9y8pmP5WA1g570EBeQ06lzAhuYFIFg37oSu9zH0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T15:10:24Z"
    mac: ENC[AES256_GCM,data:YtBfuSvsOsSs5m6J7QjEfvWyPM+jmSoAsPHIkqO8ewRgukAqIge3EWCkifJLcI3ub+bvJZYa/DK4K6vEiieBQOUv2Wr9VzeNEWd41x7Mo8QMs4gVvF20x6hF19ZV17Qt/MYbPIRf9/MXfhb6DD3JxKW2quS6zt43iDf5NmC491g=,iv:Hze/0syzcKC4hv+8WIhXi6stjnJwFRoZlYWjfHcrz/o=,tag:p8tRz57vNeOcDVCm/zkdgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
