apiVersion: v1
kind: Secret
metadata:
    name: backup-credential
    namespace: longhorn-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:si3QF29q3ndL8d0=,iv:7WbNBDOlVYaPTtZ+3THfuBsW+zmoCmna+itBBHUj+ek=,tag:kVuugiH/m3UbOMRdoTTJ6A==,type:str]
    password: ENC[AES256_GCM,data:AVNUP2vwtUbQpwab1vNH8FIAeyk=,iv:mthNNGKghGLngqjHZjlL2dPz/UZr7bGB9Ov9kVZN7RQ=,tag:o1q+IQIUDLgoT/9Ds8NilA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQjFpZHRneXBFalpSUXRC
            Z1ptclNXajQyem1xVDZGdVhhMFdJbVpucFFZCkRWK2JQYlI0TGxWK2k5ZUplZEhC
            WXVCNDdzZjRiaXBjOFhPVXVldHF6NjQKLS0tIDZxOHBrVm9lT1ZpQlZXQ0k1NG82
            ZktvVTJpUnQ1UVJUYWtObm9iYzFFQlkKyDLBDx4detamGCkIGnoRn5ixK0RZcGhG
            FnXzDPZbtpb0sEZRtJaziqE+Z73JSd00/TH7JyHJYoATJByxt+eycg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRXdtWEJQOGoyREdyRXlR
            Sm91SENHNTJEYnhOdVRjMzlPd3NVRW9lWjBFCks3clkvem1rTDZZM3BONFNuR0FR
            SGFoVGsvQ0ZRSUR6cVZoZnFxNFZpUWcKLS0tIDdocjR0b0RndWpkMVM0RVZ0MTJF
            MlpYQWY4UXNFRmZVQW9rMzlRRmtIWWMKHUSKBuCB/fv/eXNa7aCZqDoOUs+VrFut
            BGfKPZJDCCFhlG9y8pmP5WA1g570EBeQ06lzAhuYFIFg37oSu9zH0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T16:36:32Z"
    mac: ENC[AES256_GCM,data:BzK4MNDWKJsAh9u9OXjTMSmxY75JtiyIxmle/NSJfNyjntVYg+XoLAxp2WpUWnnAxPh8pxTlfOF+1GVXA25xOdTIICflwjRNSmXD/eOnk/1XrySkOgRCjt3ImId1DzYxSzmKN2Z6nwAQ4mNoOhUuDPcBnm5YnC6UpswmaxdcVR0=,iv:Hvz52nB46GfSVSlR8opIGak9MU4ftooQiU8tMlOgaZg=,tag:kDnMnafNIjmw8tyoNRFw+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
