apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |
    "backup-target": "cifs://10.10.2.2/kubernetes-backup/longhorn"
    "backup-target-credential-secret": "backup-credential"