apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
stringData:
    adminToken: ENC[AES256_GCM,data:JY/ruV2nDX5EJIk/KMiDljQFSPWB8rTByEyDd3Eh/fz4mVlRkf/51TgKuHU21UWl+JTjy9OCdwUbJH9dCa6gcnnkEHsYHsZAsKq4d3KpqQPDqR5JXbIWuaIKydOYIr+yDPPPa8hzxVWxPsXSnItv7SrAeWoDLbgrS3evPd8RodY=,iv:aS85XaHV7mJq4/6SjlhsgBJYMxgqMuKM59UhQPbuu1w=,tag:pq3smcVTuL79pDyhwLZmBw==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNE1ZUUQ1eDhBVGttTHlB
            TmpMMnVjKy9wb0dVZWI1MEZ0Q2lUVGdEVmx3ClVPcjZxQVczTmkzNjI2TlNIa0pZ
            enQxUlhSeGlUZS90dkUxWVZHK09ZMEUKLS0tIEVMUGtITGVrWVQ0RGZvaENVeVJ2
            djFZU1M5Y013Y05PbXozUS9jRTRkVUEK2NHP9wKFiZMmAbwuVGbrfeK73zs40WBs
            JExBu3QVyrh5go8cUORfM4catZsSdHg9TV9Omv6E6xrsJDVo4BINpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMVVvc1kydDZ5WDE5Nm9y
            Q0t1SkVuQ0xhY3FXUEJEa1Rmd1ZxV1ZRNFZnClF5QmdMQ0YvUE14bW9DYlAvSUlY
            MGFSRE9UaS9IdW8vZ1QzZmZTYVIrNzAKLS0tIEVPMDAzdEtDbnZqNTZkbXdsQWtF
            ZFF2VUpQTzRlaHZWR1NjMDl2ZUZvY0kKaLDoActDFU8KkuyGckyDW26tTg9LQ16f
            6KZeh8xPfhcdBlNRyD9JSExhruYhz2fX/lIru9JPTVc/elxaZ/U5IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T20:22:56Z"
    mac: ENC[AES256_GCM,data:to8cDeRPfDLnJr+4A5nyo055LsM6f+zldZJAB0Gtrn6YybqfvCLvGN+heDWfKI8pzzTgZ23lFxkh6qktjSn2ks4H5uyamvbojK6bjDR51oGacIe7nBCnNUxYAQns+FmxfVuaAva6Igm5stKh+sBNsl1XNGYPTvoKK8uk/mq9rfY=,iv:9dnbF3QRkp/hCF9zBqpefbSXED4KwQBrmqGTpLakmQo=,tag:aJVTWLwtc9rPJNjGuM8r2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
