apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
stringData:
    adminToken: ENC[AES256_GCM,data:aVLFcjW4zDXKUFOjlV6cH8B1SIOns5uASJPlRhzhob70OPgAWhEQJJ8d1G4g3PA5Ues41tUeC1WH43adEj0LuFFVdG9/wecDtA7uKo5/6FyBu5zEfGBIMFwCdhA+a7WWl5Wk3UImNgBFAu/Htaz6ZmODvGxyVA==,iv:DYAb7qGO9QLSowy7Pjuio1mkZIuL4Pqq9s5nvpn/0TE=,tag:HSm5dNPy3uMcupYHmGXxAw==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNE1ZUUQ1eDhBVGttTHlB
            TmpMMnVjKy9wb0dVZWI1MEZ0Q2lUVGdEVmx3ClVPcjZxQVczTmkzNjI2TlNIa0pZ
            enQxUlhSeGlUZS90dkUxWVZHK09ZMEUKLS0tIEVMUGtITGVrWVQ0RGZvaENVeVJ2
            djFZU1M5Y013Y05PbXozUS9jRTRkVUEK2NHP9wKFiZMmAbwuVGbrfeK73zs40WBs
            JExBu3QVyrh5go8cUORfM4catZsSdHg9TV9Omv6E6xrsJDVo4BINpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMVVvc1kydDZ5WDE5Nm9y
            Q0t1SkVuQ0xhY3FXUEJEa1Rmd1ZxV1ZRNFZnClF5QmdMQ0YvUE14bW9DYlAvSUlY
            MGFSRE9UaS9IdW8vZ1QzZmZTYVIrNzAKLS0tIEVPMDAzdEtDbnZqNTZkbXdsQWtF
            ZFF2VUpQTzRlaHZWR1NjMDl2ZUZvY0kKaLDoActDFU8KkuyGckyDW26tTg9LQ16f
            6KZeh8xPfhcdBlNRyD9JSExhruYhz2fX/lIru9JPTVc/elxaZ/U5IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T22:21:06Z"
    mac: ENC[AES256_GCM,data:ug4M5Fog4VX5V1TlyXPUpjDHZOsIlAisJdCypvqdFNnvL5Dms2KjG1llHLAn0rx9Leo5/an1i+8wdXB4qMFRyBNrdeOLzYzre1RzK4yIABWk3DDWFFjL1DeOHiGE8mfCeYKlr0OIO9iqNJC+gdhCY5ON7XMlKFsuvSn1tM1jato=,iv:eVTH+hDRamV5ch2OZYzviEuoZNXtu3FATbVfrQU8CEg=,tag:yRN18YQWE4Vcj1KqBG26cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
