apiVersion: v1
kind: Secret
metadata:
    name: slskd-soulseek
    namespace: media
type: Opaque
stringData:
    soulseek-username: ENC[AES256_GCM,data:kxSZnSqay8E=,iv:VLY8XLZevub/uttZWDkR4Z31Iso0TlFySZNjr1tBTJ8=,tag:ZIcQIc6tJuwHP/LHRgRwhQ==,type:str]
    soulseek-password: ENC[AES256_GCM,data:3I8Y8uGRZo1QvSKEbGKWQc1oK/c=,iv:b9XwRAz5BEVIX1nVUnoYf7NReQKknB5mEUVbAGnXtc0=,tag:d8K1nGm3cSHrpyj90D5HUg==,type:str]
    api-key: ""
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVjMySVcvTTZrWC9pVnF0
            bGY3TFdHZTkzek4zSlFnM2ZMUFRFTVVnTWp3CndQcnFXVlozMUllejZUNEhoWHBS
            ZmhkdlE1N01kanR0RDdDbjdBSElxemsKLS0tIFpXLzIvaUwwRFFJWnhhSXM1S1Ey
            ZjNSWGVNRm9qamcxU05jRllhRW5BdW8KHEfqANMwjGFPe5T6UGH82z5F+V5bL4mH
            AnzRGboKdkjDiXFzfGscjiTAZ6x/E3eK/8IVMB0Qh2XE032tBfmLkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K2FEVEp0K1RNc0RZb0ds
            eWJvQWVCQW03NXlyNW1RT3NYNDF3Q2RtL2lNCk1wR24yQW12ckZIVDRzMmFEUmtV
            bnlCQ0hYMDhvWDVCdDhlRlpJNWtaazQKLS0tIE9DTUh2VTIwZVdIR2o1VFpIZkJl
            c1Bpck5JaXVTUUhBaUx5alNRK252MUkK/g6+Rv3JxHZa6uacnzX+poa9Spd75XkB
            1NjT8n5tqTQgH4WxX/99pwBPPmVCAX6CeRLSyerZ1ZQYKxLKDcDE3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T01:53:15Z"
    mac: ENC[AES256_GCM,data:Bl05HhLoa7DwkAYorjQUXvRT9fmJAQ/jtZd4uHh5DcOnnuOo+8r6ZBHdN/+FD3cWCOmIor2OZxBjcysj3nRxLMi10h3nc531C5iKOrhEiMbqI+lBa3fTUStmfF6g98C20VcA7aGTQtGijGvRN1U7DaqRx2H2AhBjZTkGhFnzusQ=,iv:2sVwgZ7OoiEvRpSHdAQ+U2ZBHtytS03L/eUWrybAbX4=,tag:88nd82UW4GqTJZY2I9Hs9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
