apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-manager-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: kubevirt-manager
    repoURL: https://charts.christianhuth.de 
    targetRevision: 0.7.0
    helm:
      releaseName: kubevirt-manager
      valuesObject:
        image:
          registry: docker.io
          repository: kubevirtmanager/kubevirt-manager
          tag: "1.5.4"

        ingress:
          enabled: true
          className: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.tls: "true"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: KubeVirt Manager
            gethomepage.dev/group: Infrastructure
            gethomepage.dev/icon: kubevirt
            traefik.ingress.kubernetes.io/router.middlewares: 'traefik-forwardauth-authelia@kubernetescrd'
            external-dns.alpha.kubernetes.io/enabled: "true"
            external-dns.alpha.kubernetes.io/hostname: kubevirt.saturn.ci
            external-dns.alpha.kubernetes.io/target: direct.saturn.ci
          hosts:
            - host: kubevirt.saturn.ci
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: kubevirt.saturn.ci
              hosts:
                - kubevirt.saturn.ci

        resources: {} # TODO

        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 6

        prometheus:
          enabled: false # TODO

  destination:
    name: in-cluster
    namespace: kubevirt

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
    automated:
      prune: true
      selfHeal: true
