apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: argocd
    path: kubernetes/home/ai/openclaw

  destination:
    server: in-cluster
    namespace: ai

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true

  plugin: {}