apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: argocd
    path: kubernetes/home/apps

  destination:
    name: in-cluster
    namespace: default

  syncPolicy:
    automated:
      prune: false
      selfHeal: true

  