apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: database
type: Opaque
stringData:
    authentik-postgres-password: ENC[AES256_GCM,data:c/Sl9rKEtwe6j9Cxq6/93ogrBNGQIcGVRGcveytTXpZLcLT2a9vNpMH0uEQ0lAo1uDnKoRUlWfvaXXiqAQwQ7f/sSdLrCNOz34kLo6bfFuOXjZkhHdtZzssfD2QC5AOazJsUTrBJsAp2PP4E6hBr1gio86TS7NhEhS9mwTI/r0A=,iv:C2t8kAHsA73heAiltC5IHTdO0nVCBPYp7NUUQMRcJg8=,tag:M10QZhxKvV0U0Yymq6vZaA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY0JBU09rbzlZeG90TzR3
            RzAzcnJEYzk4K1luUkc5VjVSK0x1T3JnZVI4CmRYMXB0bUZucDFuUjZrbmtGdGxS
            b0cwbm14UzEzQ2dVQUNWVWNlaVc5Q0kKLS0tIEg1cFYxVTlGVWpLeHNkTDlzM2RT
            b05JT3E3bnRPL2tuQzNhNGhEY2IzaWsKEDh2Rk7CF8b65ZRhKczy+1EWFjpmS355
            lz9i/70YjgNQi9tVmN1Kyw98eI7o2wZvognwirnEkmI8wQpXXsAdSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdEx3NUVTMFV5MzI3ZUVP
            cnU2V1FLMXFDRUxBQU42eHFZZzJXWFBPL21JCnJwYkZKbmEyWldVSThGbUpZeVJ0
            a1AwK3JwZHpJVnNuTHpTbW1CSDZYNFUKLS0tIHdqdWxFU2RtQ1ZJaTJET0FLNjht
            bnFTS3RaVHFKNmVqMkhBZmhUZ01oME0K1YuiJ8XMH/siEqKCK7LcPCIAKFCzmBsP
            US7wUFiAyo8n29JEJxGkOOCEGi7Zp5yviojAKc5VyUDENvFcHZzagA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T16:06:11Z"
    mac: ENC[AES256_GCM,data:h1DdK9oELS/Q6KdcioBHssNaj5T1OB36ULp0F8e1vKEGTBwVizUyJ/rsW7n46TVqjECWOoqF9aPvpdsMHaj6UbnmnBNKz3ZxuNheOZXPkp+lmdzS3SRJMRRvTsZ7qBkYCyeNxUtZjYTVjEois/+uCvgb47f0f7aUTEUnTcAjnXs=,iv:LOl8JdKcdIl6zqU/2wBtxOQcYIIn2D6OUKEEf5eUhp8=,tag:0i1sZKwZDRBHOjpvtMU+hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
