apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nadiamoe
  namespace: flux-system
spec:
  type: "oci"
  interval: 1h
  url: oci://ghcr.io/nadiamoe/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: klipper
  namespace: klipper
spec:
  interval: 5m
  chart:
    spec:
      chart: kubeklipper
      version: 0.12.144
      sourceRef:
        kind: HelmRepository
        name: nadiamoe
        namespace: flux-system
  values:
    klipper:
      nodeSelector:
        "feature.node.kubernetes.io/ender3": "true"

      klipper:
        image:
          repository: mkuf/klipper
          tag: "v0.13.0"

        verbose: true

        # I don't want klipper to run out of resources. It's probably the number one priority on the cluster when printing.
        #  That said, I don't know how much it actually needs, so these are worst case really.
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 4
            memory: 4Gi

        persistence:
          virtualSDCard:
            persistentVolumeClaim:
              claimName: klipper-virtualsdcard

        securityContext:
          runAsUser: 0 # bruh
          supplementalGroups: 
            - 27 # dialout group, for serial access
          privileged: true

        config: |
          [mcu]
          serial: /dev/ttyUSB0
          restart_method: command

          [printer]
          kinematics: cartesian
          max_velocity: 300
          max_accel: 3000
          max_z_velocity: 5
          max_z_accel: 100
          square_corner_velocity: 5

          [stepper_x]
          step_pin: PC2
          dir_pin: PB9
          enable_pin: !PC3
          microsteps: 16
          rotation_distance: 40
          endstop_pin: ^PA5
          position_endstop: 0
          position_max: 235
          homing_speed: 50

          [stepper_y]
          step_pin: PB8
          dir_pin: PB7
          enable_pin: !PC3
          microsteps: 16
          rotation_distance: 40
          endstop_pin: ^PA6
          position_endstop: 0
          position_max: 235
          homing_speed: 50

          [stepper_z]
          step_pin: PB6
          dir_pin: !PB5
          enable_pin: !PC3
          microsteps: 16
          rotation_distance: 7.921
          # endstop_pin: ^PA7
          endstop_pin: probe:z_virtual_endstop
          position_min: -5
          position_max: 250

          [extruder]
          max_extrude_only_distance: 100.0
          step_pin: PB4
          dir_pin: PB3
          enable_pin: !PC3
          microsteps: 16
          rotation_distance: 6.809

          nozzle_diameter: 0.400
          filament_diameter: 1.750

          heater_pin: PC6
          sensor_type: EPCOS 100K B57560G104F
          sensor_pin: PC5
          min_temp: 0
          max_temp: 250

          control: pid
          pid_Kp: 25.80
          pid_Ki: 2.50
          pid_Kd: 66.64

          [heater_bed]
          heater_pin: PA2
          sensor_type: EPCOS 100K B57560G104F
          sensor_pin: PC4
          min_temp: 0
          max_temp: 130

          control: pid
          pid_Kp: 198.96
          pid_Ki: 38.80
          pid_Kd: 680.25

          [fan]
          pin: PA0

          [heater_fan hotend_fan]
          pin: PC0
          heater: extruder
          heater_temp: 50.0

          [bltouch]
          sensor_pin: ^PB1
          control_pin: PB0
          
          x_offset: -46
          y_offset: -26
          
          z_offset: 0.52
          
          speed: 10
          samples: 2
          sample_retract_dist: 3.0
          lift_speed: 40
          samples_result: median
          samples_tolerance: 0.050
          samples_tolerance_retries: 3

          [safe_z_home]
          home_xy_position: 157, 143
          speed: 80
          z_hop: 10
          z_hop_speed: 10

          [bed_mesh]
          speed: 120
          horizontal_move_z: 5
          mesh_min: 51, 31
          mesh_max: 230, 230
          probe_count: 5, 5
          algorithm: bicubic
          fade_start: 1
          fade_end: 10
          fade_target: 0

          [bed_screws]
          screw1: 30.5, 37
          screw1_name: front left
          screw2: 30.5, 207
          screw2_name: rear left
          screw3: 204.5, 207
          screw3_name: rear right
          screw4: 204.5, 37
          screw4_name: front right

          [screws_tilt_adjust]
          screw1: 74.5, 42
          screw1_name: front left
          screw2: 74.5, 212
          screw2_name: rear left
          screw3: 248.5, 212
          screw3_name: rear right
          screw4: 248.5, 42
          screw4_name: front right
          horizontal_move_z: 10
          speed: 80
          screw_thread: CW-M4

          [display]
          lcd_type: st7920
          cs_pin: PB12
          sclk_pin: PB13
          sid_pin: PB15
          encoder_pins: ^PB14, ^PB10
          click_pin: ^!PB2
      moonraker:
        image:
          repository: mkuf/moonraker
          tag: "v0.8.0"

        securityContext:
          capabilities:
            drop:
            - ALL

        resources:
          requests:
            cpu: 5m
            memory: 16Mi
          limits:
            cpu: 500m
            memory: 512Mi

        persistence:
          data:
            persistentVolumeClaim:
              claimName: moonraker-data

        config:
          file_manager:
            check_klipper_config_path: false
            enable_config_write_access: false
          server:
            host: 0.0.0.0
            port: 7125
            klippy_uds_address: /run/klipper/klipper.sock
          machine:
            provider: none
            validate_service: false
            validate_config: false
          authorization:
            trusted_clients: 0.0.0.0/0
            cors_domains: "*"

      ingress:
        enabled: true
        className: "traefik"
        annotations: 
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: 'traefik-forwardauth-authelia@kubernetescrd'
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: moonraker.saturn.ci
          external-dns.alpha.kubernetes.io/target: direct.saturn.ci
        hosts:
          - host: moonraker.saturn.ci
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: moonraker.saturn.ci
            hosts:
              - moonraker.saturn.ci
    mainsail:
      enabled: true

      image:
        repository: ghcr.io/mainsail-crew/mainsail
        tag: "v2.14.0"

      resources:
        requests:
          cpu: 5m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 128Mi

      config:
        defaultLocale: en
        defaultMode: dark
        defaultTheme: mainsail
        instancesDB: json
        instances:
          - hostname: moonraker.saturn.ci
            port: 443

      ingress:
        enabled: true
        className: "traefik"
        annotations:
          kubernetes.io/ingress.class: traefik
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Mainsail
          gethomepage.dev/group: Home
          gethomepage.dev/icon: mainsail
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: 'traefik-forwardauth-authelia@kubernetescrd'
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: mainsail.saturn.ci
          external-dns.alpha.kubernetes.io/target: direct.saturn.ci
        hosts:
          - host: mainsail.saturn.ci
            paths:
              - path: /
                pathType: Prefix
        tls:
        - secretName: mainsail.saturn.ci
          hosts:
            - mainsail.saturn.ci
    orcaslicer:
      enabled: true

      image:
        repository: ghcr.io/linuxserver/orcaslicer
        tag: "2.3.2"

      resources:
        requests:
          cpu: 5m
          memory: 16Mi

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: orcaslicer-config

      ingress:
        enabled: true
        className: "traefik"
        annotations:
          kubernetes.io/ingress.class: traefik
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: OrcaSlicer
          gethomepage.dev/group: Home
          gethomepage.dev/icon: orcaslicer
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.middlewares: 'traefik-forwardauth-authelia@kubernetescrd'
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: orcaslicer.saturn.ci
          external-dns.alpha.kubernetes.io/target: direct.saturn.ci
        hosts:
          - host: orcaslicer.saturn.ci
            paths:
              - path: /
                pathType: Prefix
        tls:
        - secretName: orcaslicer.saturn.ci
          hosts:
            - orcaslicer.saturn.ci
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: klipper
            patch: |
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: serial-file
                  hostPath:
                    path: /dev/ttyUSB0
                    type: CharDevice
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: serial-file
                  mountPath: /dev/ttyUSB0