apiVersion: v1
kind: ConfigMap
metadata:
  name: go2rtc-config
  namespace: printer
data:
  go2rtc.yaml: |
    streams:
      webcam: ffmpeg:device?video=/dev/v4l/by-id/usb-4K_USB_CAMERA_HD_USB_CAMERA_01.00.00-video-index0&video_size=3840x2160