apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: klipper-data
  namespace: printer
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
