apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx
    namespace: paperless-ngx
type: Opaque
stringData:
    env.PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:yoJte4gQTJLSSmDThP5hsZnoMt11qh6M7ddb187rK6pWupFxWJetmKim4J4ltmPR3T5V/oRXtjl9grhknotggLKaB8yGMGzQyIWzuqBnJvLNbpZWCmYa7/4FZA39gfiRzhEfrbaiS8KN8ixI8Ea0R7kIjDcQOMC+3DrrmfJ2xYg=,iv:MSKxDdC33GUAKqTpFMUZRbeAsgC1mQT4sIUQZKUwbNA=,tag:k7+Lkkqj5qt9jiMna7FsYQ==,type:str]
    env.PAPERLESS_DBPASS: ENC[AES256_GCM,data:VLYhTRqxiRTQR38IL8HGw5if+eK2FPL9g99msyXZm3qDXmyPMWi7F+VB+KGtxWSBNwB/QvEOncexX2Sc8fbn7kFs/mvK0Cnd5hlp4fIPvnc0IUaGImpRRzbv8zyx+vrga6xwJPl51m+Se0Sifh+VJxeY754tgMUtJ6++pjtVzkY=,iv:XpXoaDtUeNTXBIYe1cSoAOXwNzQiSgdtxtAsc23Uvxo=,tag:na4GteoGj/dC8TW/ip08Ig==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacE1CZXBRbWo0T1V0Mkc3
            cUpndlI1TnA3Q3pybWlUcVNTd05SSFZFaXhRCmFJVlptRys4dDhLeTJ5SW5OWGlP
            QXRDWXBINjRQa2RTa3BEeGszMmZuYWcKLS0tIEgzTEwrVGFhbEtIaUMzOFB6cHJo
            OC90TExlMlp5bFBycUQ5VlpLVG43b0EKDbx4sOMDuSq04DcmE5LqHgcflJezcSqF
            CSJ+KEC8b0eXCxOP3WThijBwRJoKfCTO+LTy1CQQlL6zM2xjlbiZ9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmJ6ZlVpUENsRVZmTm9D
            T1hQQnhpWnZwTGFORzBNMXllYy9BZ1hBUWpRCkd1K1dXZ0l2K0VXV214TWgxQmxi
            QmU5VmQ0RzVYVUhSL1Exdkkxa2NUNlEKLS0tIE1KdUJKYUx1M1Fzb1Y5cnZJNjht
            SlIrVlc2QmdVcGt0a01kREdMUi9pV2sKa7HJCFWSnrMRwwddlFh1R7BZg086O/ym
            Yd0n8a3vNoFR4+PBoVclQKhyLtPk1Tks3cdRlRQd3PvHtq9Zdxu4EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T22:08:35Z"
    mac: ENC[AES256_GCM,data:whI8Rlkv1ItzBH4GhG8yD78HBtqRo3YdDhMS2IsK1Hmud3VFgMt77shpwiAw9Mh6B+kT0FsJ+P1OGO+EgBJl83p5L/1ZoCyvxd4lJjVqoHzJ5TUkMHuiJ7yhuJ8OLvw5m/FQM2XZdB6fojQ6mg93cqY+cSJEBWOyldI3GwplnK8=,iv:fcODO8LknymJh4EApbiYJ2J+Y0KEsu0j+Y/raic73VE=,tag:028UxObjAgl/oZeInQLbbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
