apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:drhb6SWcxvUUllHYVz/qv5N0Nl30AagBrJ9Co8ovtzRPRTlbtgPsk4t06E4nZ4y35mJE4Cy9831Zi8OY1TMDw8ZNp1gMVlEExYJpr+lg+BdtmDciWblx1Rozuc2HouWclFUqsSaBhLSDYD2zgnIM0ypDj/YmRozZ6rdfEQ2Oq80=,iv:0VkN0nt1gfCem2Rd2iKcnXe7//eN5TPxQuSVlbS5Gug=,tag:bSE4MY6pc88mhiQihEJo0A==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:UXSSB5QM7/b+LabaBhux9c4pgHAUvtJH51VABFtiJg4wpp+nqwT6UKX6EBs32h4bEJE7Rmz56rpy4rE6tqnzILgQbgu03T68u7hmCBk/pNaoy20wwt/YcZK/zv1cwa3XWp0ld9Ie2YvbSgLwGTDnjT7QHjuskkVo/Wm6nbvzTEA=,iv:aE0q4/0kKcn5bFFu2AllVsg3WLfq5VM6mhkdIDj+8tA=,tag:2K/f8/bnVFBaaCXHb9jHvA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacE1CZXBRbWo0T1V0Mkc3
            cUpndlI1TnA3Q3pybWlUcVNTd05SSFZFaXhRCmFJVlptRys4dDhLeTJ5SW5OWGlP
            QXRDWXBINjRQa2RTa3BEeGszMmZuYWcKLS0tIEgzTEwrVGFhbEtIaUMzOFB6cHJo
            OC90TExlMlp5bFBycUQ5VlpLVG43b0EKDbx4sOMDuSq04DcmE5LqHgcflJezcSqF
            CSJ+KEC8b0eXCxOP3WThijBwRJoKfCTO+LTy1CQQlL6zM2xjlbiZ9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmJ6ZlVpUENsRVZmTm9D
            T1hQQnhpWnZwTGFORzBNMXllYy9BZ1hBUWpRCkd1K1dXZ0l2K0VXV214TWgxQmxi
            QmU5VmQ0RzVYVUhSL1Exdkkxa2NUNlEKLS0tIE1KdUJKYUx1M1Fzb1Y5cnZJNjht
            SlIrVlc2QmdVcGt0a01kREdMUi9pV2sKa7HJCFWSnrMRwwddlFh1R7BZg086O/ym
            Yd0n8a3vNoFR4+PBoVclQKhyLtPk1Tks3cdRlRQd3PvHtq9Zdxu4EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T22:28:24Z"
    mac: ENC[AES256_GCM,data:GpJIlXYB9L6LwjjVecwjpCJknY4397mN7/t+2pEZel29CWkC4z1rwIi1PyjU3cNi45fxYtxicnD4zUM1K9716iIH8k52NASEp/azJh4MNDW/GY7DFIu4xPNljjn71TT91EYeboUvmQVxw/LupSglL3nYl04p+zL/rQMTDkWQf68=,iv:JnfV3VPuVQkHboPfGQjIkCVwFYuiIVr4KAxNhK3kV6s=,tag:fEfrN3hGyfZFpUh37ilg/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
