apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:MaQy/XjTpiioCAslc0grvfAGp2Pe4WaPfpstPUYBHfOOIPZbJwnUQOtTZ4c1gP4phispua3vcqs8U3GC1C3tMCSVE/W1e0I17Mcf09npYIQGjRVS+Pr/H6O9YymYfBjw+c3f9ErD22lara+r0KJ/VaqKpUVfBuJwMOiq65ZSC74=,iv:wpszLJR5UOSU7d4dtz4uY9QZfWJoyJvXwIRWNI5JaFw=,tag:tVPWdRQdxwLDov7GZTp+9Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IMCK++s4lyZt3uRAC5RV47DQWVpgBtcYHD//3KhNLZk/4cx0y20hgk8m09sYD0A4MpwyKsHXQoZf/XxL23reUoya5M06sCJhrnhxVxAqjgRbmqJKlY4dJTsZDpPtJVAtLZeFvoPmttlnOpUtP6EWG4w5dzbFcOB/2fDhY6uBhx8=,iv:yxA1zeUhbHwRDE7MklJbq8FeEkUDp6KEwrbMj71RQjk=,tag:8KN0FMDIzTfYBLqTeB0ouA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacE1CZXBRbWo0T1V0Mkc3
            cUpndlI1TnA3Q3pybWlUcVNTd05SSFZFaXhRCmFJVlptRys4dDhLeTJ5SW5OWGlP
            QXRDWXBINjRQa2RTa3BEeGszMmZuYWcKLS0tIEgzTEwrVGFhbEtIaUMzOFB6cHJo
            OC90TExlMlp5bFBycUQ5VlpLVG43b0EKDbx4sOMDuSq04DcmE5LqHgcflJezcSqF
            CSJ+KEC8b0eXCxOP3WThijBwRJoKfCTO+LTy1CQQlL6zM2xjlbiZ9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmJ6ZlVpUENsRVZmTm9D
            T1hQQnhpWnZwTGFORzBNMXllYy9BZ1hBUWpRCkd1K1dXZ0l2K0VXV214TWgxQmxi
            QmU5VmQ0RzVYVUhSL1Exdkkxa2NUNlEKLS0tIE1KdUJKYUx1M1Fzb1Y5cnZJNjht
            SlIrVlc2QmdVcGt0a01kREdMUi9pV2sKa7HJCFWSnrMRwwddlFh1R7BZg086O/ym
            Yd0n8a3vNoFR4+PBoVclQKhyLtPk1Tks3cdRlRQd3PvHtq9Zdxu4EQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T21:26:46Z"
    mac: ENC[AES256_GCM,data:rmEUPsSoKR1eBayc+Xb3v0RVOQvBgxsv8EoVjFyrfk9NrR9bMBbVvW5O4S/O0GqywP5nKVBvrdLTLNKxYfy7xkfn9k3nV/2aUNTkMreEqlm7bwLypPQt4tPeoKY3bh2vEoHBUpRqhEIRDfV1v7540n5KkKpqgr6SztSW6p9xfrQ=,iv:tKSYhT+TZsURSp/846nAHca27iwI7jm71yOm+h4A1NM=,tag:pNg8IJCw4KDwSlsrBz8GkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
