apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  namespace: paperless-ngx
  labels:
    name: data
spec:
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: 21Ti
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: phoebe.default.svc.cluster.local/documents#data#
    volumeAttributes:
      source: //10.10.2.2/documents
      subDir: data
    nodeStageSecretRef:
      name: phoebe-smb-credentials
      namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: consume
  namespace: paperless-ngx
  labels:
    name: consume
spec:
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: 21Ti
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: phoebe.default.svc.cluster.local/documents#consume#
    volumeAttributes:
      source: //10.10.2.2/documents
      subDir: consume
    nodeStageSecretRef:
      name: phoebe-smb-credentials
      namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: paperless-ngx
  labels:
    name: media
spec:
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: 21Ti
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: phoebe.default.svc.cluster.local/documents#media#
    volumeAttributes:
      source: //10.10.2.2/documents
      subDir: media
    nodeStageSecretRef:
      name: phoebe-smb-credentials
      namespace: default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: paperless-ngx
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 21Ti
  storageClassName: smb
  volumeName: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consume
  namespace: paperless-ngx
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 21Ti
  storageClassName: smb
  volumeName: consume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: paperless-ngx
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 21Ti
  storageClassName: smb
  volumeName: media