apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spoolman
  namespace: printer
spec:
  secretName: spoolman.saturn.ci
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - spoolman.saturn.ci