apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: flux-system
type: Opaque
stringData:
    apiToken: ENC[AES256_GCM,data:tlhXV6TtjCIRb68uYDRvvM3bRSwxtqzFx2MgO7IiGkazwyfPWRKalQ==,iv:SizhXeBpL9tExZ8pQRWOaGMSFpJjav3vB8z5WLM4Hvo=,tag:iwO+LBuLhbTVN5f6NF23vA==,type:str]
    email: ENC[AES256_GCM,data:yMgfXq61xddxgdoPJHcFr0QLGYcQnH1rFzo=,iv:6GPcS2fOb4NS6B1OogmfZhpw6H2Zod1ieBf+9gmc1YI=,tag:r/Al9KkT+Fx2nwqDAaT4lg==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZnd0d0F5bkFQdnlSdllu
            bEtRMzZEU3Z2d0pMaWpNcThPamhHSVVzWjFVCit6TFNpNWcvTVdueE8wVzd6UVBK
            WmdodzRtcllmdHFnMHNOTWtMS21NclUKLS0tIG0zNkpzQVFTQUc4K1NLY2wzVkN0
            bE1QOTFhK0dxc1JId280YXNmQWZEQXcKWywIpwQGlulMScZH++pvRExTrGEKciSs
            GvsiqBG1yBhDA0V9/Glz+DzdFt+lmy/h4KMyR7ZF8rWDvMcT0G4tKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeHVKMjNGQ1pCMlNITnZw
            eEtwK3FGbmEwT0ZKOTltbE1zV1phWGJPcWlzCmdYbm5vRVFLQlNqTzdzOTE5MFQx
            QmUwbU1rQWNqZ3Vvd1RlWGlxMll6eTAKLS0tIEU4N3FkR2I4eHVoTEhUOHNYNWJY
            Y3I2cGVMeVhpZHQxTU1OUk93VmNLbGcK7k7gGbYxaJvoCSfEx8g1nT3s1bvawhma
            eQKLPYc8NjxSZFyWyl/ZO/atTGbQPtLhfkiwd8dwsLlvPXdR7p0Zcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T14:17:41Z"
    mac: ENC[AES256_GCM,data:YqSZxotbatcopZB9b2LRISLTOlBuUOiyTFXlxEw9158zevjiTjwAjnaCo+BW2KPH8MWS255OECpXcDB0+w36L6jSbj26/Ff0VSqKygAjl6uOAouvYHR9KBHItPvzQyDH8D8J/wGIH+cT+WUr+K4Obkwc2mhq6enFeRMw9zy9x5o=,iv:F/Qp1vUd98FjZBub/fsHlrntGxpvUUa8ZtYR/Pemj94=,tag:L5YgwqW63IEVzJX3ALfknQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
