apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    apiToken: ENC[AES256_GCM,data:hTHOg5JJrsk3HHlswj405Ri4JcSuS3GJ8uKZYSicSbPpryXqWGqWTmFK8l557iTc2xXRSdA=,iv:rOUWsARzubgqwqLJmZqvUdJeJI4j6oczIUJaS5PUtb8=,tag:ZcMAIJnkpvAlg3GlZbn0qw==,type:str]
    email: ENC[AES256_GCM,data:yMgfXq61xddxgdoPJHcFr0QLGYcQnH1rFzo=,iv:6GPcS2fOb4NS6B1OogmfZhpw6H2Zod1ieBf+9gmc1YI=,tag:r/Al9KkT+Fx2nwqDAaT4lg==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZnd0d0F5bkFQdnlSdllu
            bEtRMzZEU3Z2d0pMaWpNcThPamhHSVVzWjFVCit6TFNpNWcvTVdueE8wVzd6UVBK
            WmdodzRtcllmdHFnMHNOTWtMS21NclUKLS0tIG0zNkpzQVFTQUc4K1NLY2wzVkN0
            bE1QOTFhK0dxc1JId280YXNmQWZEQXcKWywIpwQGlulMScZH++pvRExTrGEKciSs
            GvsiqBG1yBhDA0V9/Glz+DzdFt+lmy/h4KMyR7ZF8rWDvMcT0G4tKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeHVKMjNGQ1pCMlNITnZw
            eEtwK3FGbmEwT0ZKOTltbE1zV1phWGJPcWlzCmdYbm5vRVFLQlNqTzdzOTE5MFQx
            QmUwbU1rQWNqZ3Vvd1RlWGlxMll6eTAKLS0tIEU4N3FkR2I4eHVoTEhUOHNYNWJY
            Y3I2cGVMeVhpZHQxTU1OUk93VmNLbGcK7k7gGbYxaJvoCSfEx8g1nT3s1bvawhma
            eQKLPYc8NjxSZFyWyl/ZO/atTGbQPtLhfkiwd8dwsLlvPXdR7p0Zcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T20:31:04Z"
    mac: ENC[AES256_GCM,data:A67YqNm//0RkYXhIrLoQKDEXYB0KnYvzqmXu6taE0LxZugCVPDroGasrZJqH45Q8OtqLt3vzTe0XjMMkWBs33WW3A5ZaQr8hJ3lMpLmpq3B5ca2fqt6mGMdbt6n7YworaW4kfPeaz5paQ49ccRuEyRt7APrC32/uRyRqkdcxpNU=,iv:06oz55VduMjCJGnRzdH1E1CYRJJ74jH7MZJAcxzbfs8=,tag:AOdEvZQGCRG7baS/ebR3YQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
