apiVersion: v1
kind: Secret
metadata:
    name: beammp-secret
    namespace: beammp
stringData:
    authKey: ENC[AES256_GCM,data:1QlninWY7xtvvdQKW1rHQGce3CH1wFGV5iLW3SKho+O0W01p,iv:KGakuo3CXIO/bC0kAsc58qOw1GnuZPI8+Gh1x9uib5M=,tag:aQ3Y/OlTFgoro079jYYyNw==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UUM3UEpNNk5jN3hPc0tS
            ZVBOYjBYank4ZkI4eXVFMXZsZ204RGlZM1djCk55aFVHNHRjTkdmMnNDaExOZGtl
            TEgwNFJ6a2JJT2Q3WW00ZEtnNHN0ZWcKLS0tIE9pd3hGRkJXQkdKeHBKY09qajNi
            UWlSZXl3RTVyS1JyWTQybTluZU1mbDQKC8XgnU8kh6DJ7deWtkTinlwmYZCUeN1C
            FRKnNcjSzWsjZldmj3UhNz6EY0+6R9RzIWVxR8ayqoB0OUMIf75a9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnlST21qRFB1b0NPVzBD
            YzA1OFhGZ2d4RzF6RVltNXhmQXI2T2VOWTIwCllJS2NQWGJBOWkyUTdxaHhLajg4
            bWYxTUVUSEdyZEJEWHZKTTBVUzkzWEkKLS0tIDQ5VWpHTEcrOEcwVHFOdFZVZ05J
            bkNWaTMrMmJNakxaSnBjY0tqWDdxMDgKRP2I5ZcgJN/KoF3hhYMinXePeof58Gav
            eQhQIMZuQF392ywu/RksLlHG3PFT66fq/LPaxD5MtY5I2HyrVwwqnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T22:49:31Z"
    mac: ENC[AES256_GCM,data:k6v36Jk3J8nMPqtD6GUqQ5hqbZeZLSHVuXSKXSgBwuaTddv7uYI0NftsUS/38BaDDwbeRiIV0hyeNQlL4MEoGnPuWUJj7qJtOcxVHlHPriP8G9PllIkKwg7vz67O4qp8jF28uRxusA1ZryqQVj9d1IaWDwZpYhrUgvTZpAj/Zh4=,iv:GG6n0cW8tD2VyECALMwZbTMFnFFYySCt6d551uLzEGo=,tag:osO1WXzuIiZddg8V1lMNUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
