apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfd-custom
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: argocd
    path: kubernetes/infra/nfd/custom

  destination:
    server: in-cluster
    namespace: node-feature-discovery

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true

  plugin: {}