apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../ai/app.yaml
  - ../external/app.yaml
  - ../games/app.yaml
  - ../homepage/app.yaml
  - ../mail/app.yaml
  - ../media/app.yaml
  - ../paperless/app.yaml
  - ../printer/app.yaml
  - ../syncthing/app.yaml
  - ../vaultwarden/app.yaml