apiVersion: v1
kind: Service
metadata:
  name: &appName ustreamer
  namespace: printer
spec:
  selector:
    app: *appName
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
