apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: argocd
    path: kubernetes/infra/hardware/intel

  destination:
    name: in-cluster
    namespace: intel

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true

  plugin: {}