apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: argocd
    path: kubernetes/infra/hardware/intel/app

  destination:
    name: in-cluster
    namespace: intel

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
    automated:
      prune: true
      selfHeal: true

  