apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: master
    path: kubernetes/infra/hardware/intel

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true