apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: argocd
    path: kubernetes/home/mail

  destination:
    name: in-cluster
    namespace: mail

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
    automated:
      prune: false
      selfHeal: true

  