apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-misc
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: argocd
    path: kubernetes/infra/misc

  destination:
    server: in-cluster
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true

  plugin: {}