apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: auth
type: Opaque
stringData:
    authentication.ldap.password: ENC[AES256_GCM,data:rD8MV0ynhjr0egMoh4EKdydYWjSrLA0spfgesvvAjWETC/KH5dx/oGqZmNsNTGTC4zQ597ofC5+jBabBK/nrRVsdZSZQO7jtOnNGM6mYemzdoRfbiootDuEBOl+5A8hUGwwbMWuwVZaF6LluSfa1qrXOrLfo2ofN8F+o0tPY1VI=,iv:H3MYwrB/i+NCN90fM9Ui7UewML8aC9n6AuhQZiQ77NQ=,tag:If/ubpzXDfrWyFb0wQUktA==,type:str]
    session.encryption_key: ENC[AES256_GCM,data:hwbWzzW1FgJzwZXceILTDP69k2KIV5uBaAGmf/YwvqpWVLh5YY/yEsrO8HAbU7C8teC6uHqyBelyOpc1PJwEnWOn2HZ8XR550UoFQWKLwgidVYui/GDn5KG2fCyoG0OR6oymurMsd8soxm7o/GuQ/kGCib1kP7gt/sKoUerip9s=,iv:o1W6voe7oGdl/O2xnp+GsSJx3sD9YJ9NTZU/1rek44U=,tag:K/ayRaAZw0F+gX73qYf9BA==,type:str]
    storage.postgres.password: ENC[AES256_GCM,data:119U3QM8s7NqXPHMHqvLTlwboeMG2nC2PoKVLomUcOYXFmID2GEJJX/P4zHVLoKurkRISy3fctMpoZ3o0/dllUMvAMUUTxczZau/sDOVpAP9RZrF83LuVFIl2wyu2sa5yV7es2yz/sw1v4G4JtH+pUHvHLyPcKBw3RzhV+dTYRQ=,iv:6bdIGtngraDyw3Vy8psshtpCyDgAoIygo1tPtiqCrM4=,tag:S1DMfGWr5ES3ksA2gHDU5w==,type:str]
    storage.encryption_key: ENC[AES256_GCM,data:c/hUD9Ay77kVXj5New1hpnkO28AooNxwpT5/sdioJ+IHsyTgF3K0SeCcgTtCGm8UzYJog732UxxC9QBVrJ5sli2atbaFzwr4rfKt/yl2XEh1cpb/cxRbwJuqj8FZrq2gvH27dan9Bip3oQx+eXzIMgR8dwW0FWoQJ1HM1guZtcc=,iv:gQo9fjOwuadUJ2eGtWuivNyI397NWlrHMJeU64qFGKI=,tag:/6eaIv4SYzIDYJOu4rd+Ww==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUmYvQkFpV05WdzNERU91
            TWsweWJhRDlRZ2ZLMmowWHhJV2orcXhNQTNJCmVDWlB3RkREbkQ5MlZXMGRFbUtq
            emVxMzNwSHJMc3cwYlU4S1NmdnkyeGsKLS0tIFo2TTh3ZDJhbmwyTFpiRDlVZXZC
            MzdFcGlsaXJiczdnWEtHRnlaSlBJTnMKgeQJOu9XQKHmnbh3l+oq1QSjM82jpYxK
            YUjlxkFp44fcvJ1mGh8IiJsfPp+WlAJotshP/5SpK0xxgCAWNqcZfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTllLMW9FMFMyd080THgx
            bVNOSjhSZ2ZFajQyZmFITm9rcjZZTjRVSHdZCjBmdU5maEEwTW44cmNzenZwVEhD
            c0hzZUZjcEpIZzlKLzUwbjFteFJIYVUKLS0tIHdOMnErNUw1TVhPZ2V4dzcydHNI
            WS91SFgyY1dJeVcwL1k2TExHV3BLUjQKi47a+OUwry0WGZ1c4uFQ5xq/LoQwFcF7
            xWleeVXwTjXjCL4+rzbZeso5OLPMmpDgEs/rq4X/ZlhqE0Ow168+ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T01:10:51Z"
    mac: ENC[AES256_GCM,data:54u9Sa6NtFt8WvAbtfUfZkZ6VokxHhIrjoDXdDFx59BBbedk+YAsRZgjdSqoE6Dz+QrFpqw09XRVA7QynPoY7qyNbOPrMRR1wl0cci8IOtO/a3RDT3govHJ1cAHb0i3UxJolgJMe7is4vX5E831ilfMswlYHgp79I3SLXX+njng=,iv:QJrMQaS7nSi/gv4qAuLe2DYegduOuhJdI0M9oN59j0A=,tag:sbEoOx7e3XfQWVSNMV/XjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: authelia
    # todo
    namespace: database
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:CnoHZrhCIRu7YVyBZCQ+FyZNZQMNIusKlqUkwp0BYrl+3I44/0PeMI7NVBkJd1QxACJGERx8PEVgqrax2MG/5EvUXSoVi85+b2bqaZr5JvHRGC7/obU0RKNiuNwqq5xf/CZfh/azNjQIjducRqUkIGprKjVzKBLizK8Qp0sexeg=,iv:vzN05qlCTCfJkm5O/tlvgRD60WJRzM9GGqKThV8Ubg8=,tag:7VX20c9akxyre+alz4t1pA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUmYvQkFpV05WdzNERU91
            TWsweWJhRDlRZ2ZLMmowWHhJV2orcXhNQTNJCmVDWlB3RkREbkQ5MlZXMGRFbUtq
            emVxMzNwSHJMc3cwYlU4S1NmdnkyeGsKLS0tIFo2TTh3ZDJhbmwyTFpiRDlVZXZC
            MzdFcGlsaXJiczdnWEtHRnlaSlBJTnMKgeQJOu9XQKHmnbh3l+oq1QSjM82jpYxK
            YUjlxkFp44fcvJ1mGh8IiJsfPp+WlAJotshP/5SpK0xxgCAWNqcZfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTllLMW9FMFMyd080THgx
            bVNOSjhSZ2ZFajQyZmFITm9rcjZZTjRVSHdZCjBmdU5maEEwTW44cmNzenZwVEhD
            c0hzZUZjcEpIZzlKLzUwbjFteFJIYVUKLS0tIHdOMnErNUw1TVhPZ2V4dzcydHNI
            WS91SFgyY1dJeVcwL1k2TExHV3BLUjQKi47a+OUwry0WGZ1c4uFQ5xq/LoQwFcF7
            xWleeVXwTjXjCL4+rzbZeso5OLPMmpDgEs/rq4X/ZlhqE0Ow168+ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T01:10:51Z"
    mac: ENC[AES256_GCM,data:54u9Sa6NtFt8WvAbtfUfZkZ6VokxHhIrjoDXdDFx59BBbedk+YAsRZgjdSqoE6Dz+QrFpqw09XRVA7QynPoY7qyNbOPrMRR1wl0cci8IOtO/a3RDT3govHJ1cAHb0i3UxJolgJMe7is4vX5E831ilfMswlYHgp79I3SLXX+njng=,iv:QJrMQaS7nSi/gv4qAuLe2DYegduOuhJdI0M9oN59j0A=,tag:sbEoOx7e3XfQWVSNMV/XjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
