apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
    namespace: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:PhcKgr3RTkpOcCtyDqtqEXi4dPKjzbooURa1XTp2zBUO6t0M23kC5KUuVYIteVGhELmYM+K0JcCmsu+IKeoeWYctHoR9FybX5J+426KUrmbdX9Q+RJnK139Mgb6GD3MfuN44GPTaitf+eA5ivisXDFb/CqK/OEIgllkQ0HP3hzM=,iv:lebsgdy9kgnSrzJlf2Mf6D83ct2V194zirfffK16QpE=,tag:NYm/KgGPsoP3B9qO/ptTww==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:seYab0hWR4pqGiMIGge4enluPNiRYYQ+aV5qtsUwUmCZHqcBPYb7bQjAmIYhpSay6YBZGa3ZTEsbDKB23mItr19VCetcQQ==,iv:CueDUxb08tl0ehz3UtP85VWdTrUxkyIXFgOaDqbJ6lU=,tag:Zyx4GhcS/tseRMshA0LwAA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd1VZZmNGdHZCclBjaERt
            TG02M1FuekYzVGd3ZHhQWEhiYXcxUHlpbzJZCi9ibThGV0cybnRHbUxROWNxdmcr
            ZjZDR3ZqYkdLZjRRQjFtczhNL0EzTmcKLS0tIHZVWjZrRy9VSllnbWVCT0t2ODYr
            Q0QyNys1WllBbzM1dEhqdHV2QSthQnMK4JTEDgxiehsc/ioHSt8yvmSBS8Gc7/RP
            oydm/oaVfLEnl7St22Ke7C/9M3FZSbgBXXwRXeTEMdbc7kcE2CvF4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSUc5TzdGSDNVYk9icjB2
            b1B6R1NhQm1lQjNmQkZFL1cxN3FIOEdFZFVVCkdZK24ydFNZREV0dzVKMEcyTkc1
            Q2NCdi9EYzhDTytVMkFmRW5WV2V5bW8KLS0tIHVkUFNXcjdvMjJxcFg2WjlLRVV2
            Ri9VTjl4V2xYVzRFM1ZPTVdBQjZFalkKaXrZJnXh9jMZCZYgYI8Hh7XyFqlSb0X+
            LzJHNMmY6i8gnlBrVMPN72uIUqSHrO7AuDjcLYBUFYUZZreNdhFxHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T17:08:44Z"
    mac: ENC[AES256_GCM,data:fMa/b9RkjQlHEvWmu6qO10TC7UWjgkLRsSQhDFvsJ1Hy34XW1St2d3LtjZuLqPDoTcF0C3E9F7bMtZxu/NX6sBkGLjB0HZGgptYZKWbcD0kuyi40BRNhQOy5bX0+PJ89IlUH9HWS0nAB59gw839xcFGX+szTFyZM7XDK64qIZYI=,iv:5K8cd7c1kzK83RuON7n2coz7dYhssEiuHC4DdMOV9/Y=,tag:FmxqSSC3oSq/rh5pB9b9PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
