apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-storage
  namespace: flux-system
spec:
  interval: 5m
  path: kubernetes/media/storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-fluxcd
      namespace: default