apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: media
  labels:
    name: media
spec:
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: 21Ti
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: phoebe.default.svc.cluster.local/media##
    volumeAttributes:
      source: //phoebe-truenas.local/media
    nodeStageSecretRef:
      name: phoebe-smb-credentials
      namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
  namespace: media
  labels:
    name: downloads
spec:
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: 21Ti
  storageClassName: smb
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: phoebe.default.svc.cluster.local/media#downloads#
    volumeAttributes:
      source: //phoebe-truenas.local/media
      subDir: downloads
    nodeStageSecretRef:
      name: phoebe-smb-credentials
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: media
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 21Ti
  storageClassName: smb
  volumeName: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 21Ti
  storageClassName: smb
  volumeName: downloads