apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobrr
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: autobrr
  template:
    metadata:
      labels:
        app: autobrr
    spec:
      containers:
        - name: autobrr
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 256Mi
          image: ghcr.io/autobrr/autobrr:v1.74.0
          ports:
            - containerPort: 7474
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: autobrr-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autobrr-config
  namespace: media
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: autobrr
  namespace: media
spec:
  selector:
    app: autobrr
  ports:
    - port: 7474
      targetPort: 7474
      protocol: TCP
      name: http
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: autobrr
  namespace: media
spec:
  secretName: autobrr.saturn.ci
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - autobrr.saturn.ci
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autobrr
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Autobrr
    gethomepage.dev/group: Media
    # gethomepage.dev/widget.type: autobrr
    # gethomepage.dev/widget.url: http://autobrr.media.svc.cluster.local:7474
    # gethomepage.dev/widget.key: "${AUTOBRR_API_KEY}"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: 'traefik-forwardauth-authelia@kubernetescrd'
spec:
  tls:
    - secretName: autobrr.saturn.ci
      hosts:
        - autobrr.saturn.ci
  rules:
    - host: "autobrr.saturn.ci"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: autobrr
                port:
                  number: 7474
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: autobrr
  namespace: media
spec:
  endpoints:
    - dnsName: autobrr.saturn.ci
      recordType: CNAME
      targets:
        - direct.saturn.ci
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"