apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: qbittorrent
          image: linuxserver/qbittorrent:5.1.4
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TORRENTING_PORT
              value: "20006"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 20006
              protocol: TCP
            - containerPort: 20006
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  selector:
    app: qbittorrent
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 20006
      targetPort: 20006
      protocol: TCP
      name: torrent-tcp
    - port: 20006
      targetPort: 20006
      protocol: UDP
      name: torrent-udp
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent
  namespace: media
spec:
  secretName: torrent.saturn.ong-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - torrent.saturn.ong
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    "kubernetes.io/ingress.class": traefik
    "traefik.ingress.kubernetes.io/router.tls": "true"
    "external-dns.alpha.kubernetes.io/hostname": torrent.saturn.ong
    "external-dns.alpha.kubernetes.io/target": direct.saturn.ong
spec:
  tls:
    - secretName: torrent.saturn.ong-tls
  rules:
    - host: "torrent.saturn.ong"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: torrent
                port:
                  number: 8080
    - host: "torrent.internal"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: torrent
                port:
                  number: 8080