apiVersion: apps/v1
kind: Deployment
metadata:
  name: slskd
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: slskd
  template:
    metadata:
      labels:
        app: slskd
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: slskd
          image: slskd/slskd:0.24.5
          env:
            - name: SLSKD_REMOTE_CONFIGURATION
              value: "true"
          ports:
            - containerPort: 5030
              protocol: TCP
            - containerPort: 50300
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: data
            - mountPath: /media
              name: media
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: slskd-data
        - name: media
          persistentVolumeClaim:
            claimName: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: slskd
  namespace: media
spec:
  selector:
    app: slskd
  ports:
    - port: 5030
      targetPort: 5030
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: slskd-p2p
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.254.3
  selector:
    app: slskd
  ports:
    - port: 50300
      targetPort: 50300
      protocol: TCP
      name: soulseek-p2p
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slskd
  namespace: media
spec:
  secretName: slskd.saturn.ong-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - slskd.saturn.ong
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slskd
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/hostname: slskd.saturn.ong
    external-dns.alpha.kubernetes.io/target: direct.saturn.ong
spec:
  tls:
    - secretName: slskd.saturn.ong-tls
  rules:
    - host: "slskd.saturn.ong"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: slskd-http
                port:
                  number: 5030