apiVersion: apps/v1
kind: Deployment
metadata:
  name: slskd
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: slskd
  template:
    metadata:
      labels:
        app: slskd
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: slskd
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 640Mi
          image: slskd/slskd:0.24.5
          env:
            - name: SLSKD_REMOTE_CONFIGURATION
              value: "true"
          ports:
            - containerPort: 5030
              protocol: TCP
            - containerPort: 50300
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: data
            - mountPath: /media
              name: media
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: slskd-data
        - name: media
          persistentVolumeClaim:
            claimName: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-data
  namespace: media
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: slskd
  namespace: media
spec:
  selector:
    app: slskd
  ports:
    - port: 5030
      targetPort: 5030
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: slskd-p2p
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.254.3
  selector:
    app: slskd
  ports:
    - port: 50300
      targetPort: 50300
      protocol: TCP
      name: soulseek-p2p
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slskd
  namespace: media
spec:
  secretName: slskd.saturn.ci
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - slskd.saturn.ci
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slskd
  namespace: media
  annotations:
    kubernetes.io/ingress.class: traefik
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: slskd
    gethomepage.dev/group: Downloads
    gethomepage.dev/icon: slskd
    # gethomepage.dev/widget.type: slskd
    # gethomepage.dev/widget.url: https://slskd.saturn.ci
    # gethomepage.dev/widget.key: "${SLSKD_API_KEY}"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: 'traefik-forwardauth-authelia@kubernetescrd'
    external-dns.alpha.kubernetes.io/enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: slskd.saturn.ci
    external-dns.alpha.kubernetes.io/target: direct.saturn.ci
spec:
  tls:
    - secretName: slskd.saturn.ci
      hosts:
        - slskd.saturn.ci
  rules:
    - host: "slskd.saturn.ci"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: slskd
                port:
                  number: 5030