apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-helm
  namespace: argocd
spec:
  source:
    chart: cloudnative-pg
    repoURL: oci://quay.io/jetstack/charts
    targetRevision: 0.29.0

  destination:
    server: in-cluster
    namespace: cnpg-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true