apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: router
  namespace: external
spec:
  endpoints:
    - dnsName: router.saturn.ci
      recordType: CNAME
      targets:
        - direct.saturn.ci
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"