apiVersion: v1
kind: Secret
metadata:
    name: oidc-grafana
    namespace: monitoring
type: Opaque
stringData:
    oidc.client_secret: ENC[AES256_GCM,data:7QU2UW+u0b2VtaW9AazVHdzZp5UzDh7sM/JhVc1i2k2F4TBx4Y5MSjvJF4KOenHxclrCK0TUAFGSxCSfpDHHmylQf8EH2nZP,iv:OFtRhQqXpZoiq8blYB8itA/o2sb8R+FyTpX+To0tTC8=,tag:8ATq9E/r2ABGfuGsKEsS2g==,type:str]
    oidc.client_secret_digest: ENC[AES256_GCM,data:ZFkEKX3BmKkAowcI/C203Ww2ky/0LNZPDLc+apllwxnmoA35ZbQDxMUbFe/l8S0bV1Y+YZYhpQZkyYo1L3P13c6fdLaOXKAZm8f6RcsYCO+FV3wAm2ygJMwcmCW5PeBRbOLdr4YtFKHxTrwtlLujk/nUvkkGfiEMAQGSYlg3RM2suXg=,iv:E1cBzyX9mRv/6yIkU21pOv37fBe+IPFbY+9ztyKv2N8=,tag:UuMc5wgVKBxyFgiliY1dUA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTk1TWitBVWtQNWZIKzdw
            QmdhWUpldE51WmZBMVlwUGk1SE9jamNJL0NRCm5pMUtRMkcrQkxyRzZpSDdNTHE0
            ZjdaQk9LdURaZ2JhYkdoQmV6UE93azQKLS0tIGRRN0ZLNXBxMnQ1SzVhY0FCUkdC
            V01aVGw1ME5hVlNzb3AyZkRJUkpUbU0KZLNETGVObNueopp0FIAN4puAEDFndlOo
            /QuJ0+ajHWD/Bk0j+6otHnCqvwFutr/9uIhwJaxuEibTDGI/Zpi69w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bThza3hBenFmSG1VWlJq
            aGREN0syUzBaalZsd0hTYXZ6NTBjc3l6d2ljCldyRWNRV1FCV0RhOUtxZ2xrUFYx
            cUIzbmY5bTVmUUZlV3RjY01QeHlNOXMKLS0tIGxVZnlrNmdVNEYxV1NmcjBEUFk5
            RVVTb0UwZmo1MEpjTkswUExoclo1VjAKAAkMRdwNMnazGD7b10i9H2wtEmP56sdw
            vqmNGaTED6kARn66TiAOWO+LTgKzA4xWBJ72MB9T6BglRR/QQFmtgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T21:51:47Z"
    mac: ENC[AES256_GCM,data:NIGrJLz8r//khG0TADh7e+JVkvgjB9yGsoOLwW3a/WPO32sl6EzYuOMDlLHgAsMjyt/Py/Ev6eq061+jbANZ6SmSE4Qg3PwqAuKKcIM63c0T/nG0rNX6TKCaDpYz/pkkxTLDzHURwCTIUQj0KV3otWAN7X1ps+sklYIU32fUifU=,iv:VOCE2gGllXqo5g0c0cBfG4+x/rT1YExGPCpdULOpToY=,tag:vHtnvAGs41YMpbzLLP17zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
