apiVersion: v1
kind: Secret
metadata:
    name: oidc-grafana
    namespace: monitoring
type: Opaque
stringData:
    oidc.client_secret: ENC[AES256_GCM,data:yA+asq4S/UE=,iv:Lsbt1gfD9YJV2sqLq9w9DsowTlpcxOi9fscX7ezmX2M=,tag:ubXwPyPMHMslHG33FvY6NQ==,type:str]
    oidc.client_secret_digest: ENC[AES256_GCM,data:XY9l5KD15VM=,iv:z0pIxJnl9q4nbOwQHe/bVTmQwyKN3kM3qJebev1U3PI=,tag:3aZ+bTF1ipIiRW62nruIEg==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTk1TWitBVWtQNWZIKzdw
            QmdhWUpldE51WmZBMVlwUGk1SE9jamNJL0NRCm5pMUtRMkcrQkxyRzZpSDdNTHE0
            ZjdaQk9LdURaZ2JhYkdoQmV6UE93azQKLS0tIGRRN0ZLNXBxMnQ1SzVhY0FCUkdC
            V01aVGw1ME5hVlNzb3AyZkRJUkpUbU0KZLNETGVObNueopp0FIAN4puAEDFndlOo
            /QuJ0+ajHWD/Bk0j+6otHnCqvwFutr/9uIhwJaxuEibTDGI/Zpi69w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bThza3hBenFmSG1VWlJq
            aGREN0syUzBaalZsd0hTYXZ6NTBjc3l6d2ljCldyRWNRV1FCV0RhOUtxZ2xrUFYx
            cUIzbmY5bTVmUUZlV3RjY01QeHlNOXMKLS0tIGxVZnlrNmdVNEYxV1NmcjBEUFk5
            RVVTb0UwZmo1MEpjTkswUExoclo1VjAKAAkMRdwNMnazGD7b10i9H2wtEmP56sdw
            vqmNGaTED6kARn66TiAOWO+LTgKzA4xWBJ72MB9T6BglRR/QQFmtgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T21:31:49Z"
    mac: ENC[AES256_GCM,data:bHlLhRJFO0pfUnsjNT4HZfRq46To2WByG7aSoW6o5m8mGQdkrW9ybgtLBugC5mvC4ppvLmUE8ufPq/SH8wHDR1ObyXpdGQS27ORO6+yaK7EsiV+YQttXUFdBxgJN8NSHv2/wwS7lSNupYbdw5eB27QoY+SQ50UnoyjuDRYdXVrM=,iv:+8aJoC3TS3D3dTJ8MwwVA9Yt494oM1p8WxrIDdbz1ws=,tag:x8Sgm+uYW2RvQgcJcwbUwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
