apiVersion: v1
kind: Secret
metadata:
    name: stalwart-database
    namespace: mail
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vKaYNxFj1RcJ+x6VMQTtAzwu1uueHv+NIKAfO9uTXOvMj6Dr+MexSJIgNOlg2vnASSlfKdZgp/So3v+oj0Vkb4tWEsLlfvBSjDLANB/Cc5Zksq5DnKg/QtOl48qauMV7BT1Ewc7H9jJmrBWAttmVZSarBRyGRtWnXTX/3M9rf6o=,iv:9UL8YLnJjy4DiYAEDLjfA0MWYsASl3Gw3fipQ/DEONc=,tag:giCIvLa3GWHzr1t/856cAg==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UUM3UEpNNk5jN3hPc0tS
            ZVBOYjBYank4ZkI4eXVFMXZsZ204RGlZM1djCk55aFVHNHRjTkdmMnNDaExOZGtl
            TEgwNFJ6a2JJT2Q3WW00ZEtnNHN0ZWcKLS0tIE9pd3hGRkJXQkdKeHBKY09qajNi
            UWlSZXl3RTVyS1JyWTQybTluZU1mbDQKC8XgnU8kh6DJ7deWtkTinlwmYZCUeN1C
            FRKnNcjSzWsjZldmj3UhNz6EY0+6R9RzIWVxR8ayqoB0OUMIf75a9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVnlST21qRFB1b0NPVzBD
            YzA1OFhGZ2d4RzF6RVltNXhmQXI2T2VOWTIwCllJS2NQWGJBOWkyUTdxaHhLajg4
            bWYxTUVUSEdyZEJEWHZKTTBVUzkzWEkKLS0tIDQ5VWpHTEcrOEcwVHFOdFZVZ05J
            bkNWaTMrMmJNakxaSnBjY0tqWDdxMDgKRP2I5ZcgJN/KoF3hhYMinXePeof58Gav
            eQhQIMZuQF392ywu/RksLlHG3PFT66fq/LPaxD5MtY5I2HyrVwwqnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T01:46:39Z"
    mac: ENC[AES256_GCM,data:Ua2pvFfctwczaad+dvF4xGbOchiV19Wej7Ws6x/d41Y0zy3RH43YCZ4mt7Sr+ekv2D7rMbjzpNRd82OBTgAqLz3yp2efgVWiEe9QMibPORUVg3TBxPFAB5240rT572dj2cJRQK34iKGXqAV3V5mBfzGhZNlP/BcjHV+gNHVjTvw=,iv:Q3QmiUgKIvAbO+5lX7q+sS9RilqQXUO73Sq5phOvIPU=,tag:zyLq6SourQHU+1mm5c/TBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
