apiVersion: v1
kind: Secret
metadata:
    name: oidc-stalwart
    namespace: mail
type: Opaque
stringData:
    oidc.client_secret: ENC[AES256_GCM,data:a2yAXg1h9UmCMzw4RV5DVxenvEqFymAdQmfBuye7AAU5ruGoAWSijwXJbVAH2QSRE7nzHv0Vn3bs+o/D0UBk0kod5A1Kk4GT,iv:JATCmuy5e7pOdvylk8onVju0PiIKsDAUE3Go+ax/gfk=,tag:hbcEGJPuRUk3TtJZ7/FpXg==,type:str]
    oidc.client_secret_digest: ENC[AES256_GCM,data:xyl56h/C/eOc3E8X3gsjJLaHDihd9oirK2pjDMN71twga6U5Q6TXfy+pl/A4PaKn+Yz1tB9AGlDCp8s3fgqVPI9sDEqfIMu368xY+Jncnv560e4w6foRQTW4r9uCZNT3f0qrzsP2bRMSHdom98s3KvnXOH7jTIpPg5XXx/7M5dJZvlQ=,iv:RHWJwjbjBHdM6V2LjPaJV0Y2mpvVnDsh7VvBJxDo7aU=,tag:7Tx2DvYSD6VY2um2fqdJ2w==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTk1TWitBVWtQNWZIKzdw
            QmdhWUpldE51WmZBMVlwUGk1SE9jamNJL0NRCm5pMUtRMkcrQkxyRzZpSDdNTHE0
            ZjdaQk9LdURaZ2JhYkdoQmV6UE93azQKLS0tIGRRN0ZLNXBxMnQ1SzVhY0FCUkdC
            V01aVGw1ME5hVlNzb3AyZkRJUkpUbU0KZLNETGVObNueopp0FIAN4puAEDFndlOo
            /QuJ0+ajHWD/Bk0j+6otHnCqvwFutr/9uIhwJaxuEibTDGI/Zpi69w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bThza3hBenFmSG1VWlJq
            aGREN0syUzBaalZsd0hTYXZ6NTBjc3l6d2ljCldyRWNRV1FCV0RhOUtxZ2xrUFYx
            cUIzbmY5bTVmUUZlV3RjY01QeHlNOXMKLS0tIGxVZnlrNmdVNEYxV1NmcjBEUFk5
            RVVTb0UwZmo1MEpjTkswUExoclo1VjAKAAkMRdwNMnazGD7b10i9H2wtEmP56sdw
            vqmNGaTED6kARn66TiAOWO+LTgKzA4xWBJ72MB9T6BglRR/QQFmtgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T03:14:05Z"
    mac: ENC[AES256_GCM,data:XI9O4dlqGUSK4KVM1M09amC08eob9KbvHZYtrzv9hwGItHF5ezkH9LeQ6vJmojHnOv+xO7tn91CDl/9thzFEw9QRqj3Ntnzw3Kfj7z4UgwIDRGIQ8kOUoEueO6oB6kKxjbZ3PFlEWiA0SlavspzCykt7ziz3coVqOfxXvJoIMQI=,iv:jrJaa1rGqXzHs63lxmOnlUVlmktcLneXX6hAhyGpdGs=,tag:GpCJcQLjg5qbs7j7ozOh1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
