apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-terrafermagreg-modern-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: minecraft
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 5.1.3
    helm:
      releaseName: terrafermagreg-modern
      valuesObject:
        image:
          repository: itzg/minecraft-server
          tag: 2026.8.1-java21-jdk
          pullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 1
            memory: 4096Mi
          limits:
            cpu: 4
            memory: 8192Mi

        extraEnv:
          INIT_MEMORY: 4096M
          MAX_MEMORY: 8192M
          
          GENERIC_PACK: "https://github.com/TerraFirmaGreg-Team/Modpack-Modern/releases/download/0.13.7/TerraFirmaGreg-Modern-0.13.7-serverpack.zip"

        livenessProbe:
          initialDelaySeconds: 300 # 5 minutes

        workloadAsStatefulSet: true
        strategyType: OnDelete

        minecraftServer:
          eula: "TRUE"
          type: FORGE
          version: 1.20.1
          forgeVersion: 47.4.13
          whitelist: "Baconing,TickleKnees,Kamieo_"
          ops: "Baconing"
          overrideServerProperties: false
          
          modUrls: []

        persistence:
          labels:
            recurring-job-group.longhorn.io/backup: enabled
          storageClass: longhorn
          dataDir:
            enabled: true
            Size: 16Gi
            accessModes:
              - ReadWriteOnce

        serviceAnnotations:
          mc-router.itzg.me/externalServerName: tfgm.saturn.ci,tfgm.local
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: tfgm.saturn.ci
          external-dns.alpha.kubernetes.io/target: direct.saturn.ci
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas

  destination:
    name: in-cluster
    namespace: minecraft

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true

  