apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao
  namespace: openbao
spec:
  secretName: openbao.saturn.ci
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - openbao.saturn.ci