apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 39.0.5
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    service:
      spec:
        loadBalancerIP: 10.10.254.0
    api:
      dashboard: true
    ingressRoute:
      dashboard:
        enabled: true
        annotations: 
          kubernetes.io/ingress.class: traefik
          gethomepage.dev/enabled: "true"
          gethomepage.dev/href: "https://traefik.saturn.ci" # Need this when using Traefik IngressRoutes
          gethomepage.dev/name: Traefik
          gethomepage.dev/group: Network
          gethomepage.dev/icon: traefik-proxy
          traefik.ingress.kubernetes.io/router.tls: "true"
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: traefik.saturn.ci
          external-dns.alpha.kubernetes.io/target: direct.saturn.ci
        matchRule: Host(`traefik.saturn.ci`)
        services:
          - name: api@internal
            kind: TraefikService
        entryPoints: 
          - "websecure"
        middlewares:
          - name: forwardauth-authelia
            namespace: traefik
        tls:
          secretName: traefik.saturn.ci
    ports:
      websecure:
        http:
          middlewares:
            - traefik-forwardauth-authelia@kubernetescrd
