apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flannel-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: flannel
    repoURL: https://flannel-io.github.io/flannel/
    targetRevision: v0.28.9
    helm:
      releaseName: flannel
      valuesObject:
        podCidr: "10.42.0.0/16"

        flannel:
          image:
            repository: ghcr.io/flannel-io/flannel
            tag: v0.28.9
          flannel_cni:
            image:
              repository: ghcr.io/flannel-io/flannel-cni-plugin
              tag: v1.9.1-flannel3
          
          cniBinDir: "/opt/cni/bin"
          cniConfDir: "/var/lib/rancher/k3s/agent/etc/cni/net.d"
          
          backend: "vxlan"
          mtu: 1340

          cniConf: |
            {
              "name":"cbr0",
              "cniVersion":"1.0.0",
              "plugins":[
                {
                  "type":"flannel",
                  "delegate":{
                    "hairpinMode":true,
                    "forceAddress":true,
                    "isDefaultGateway":true
                  }
                },
                {
                  "type":"portmap",
                  "capabilities":{
                    "portMappings":true
                  }
                },
                {
                  "type":"bandwidth",
                  "capabilities":{
                    "bandwidth":true
                  }
                }
              ]
            }

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

  destination:
    name: in-cluster
    namespace: kube-flannel

  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
    automated:
      prune: false
      selfHeal: true

  