apiVersion: v1
kind: Namespace
metadata:
  name: helm
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-kyverno
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/helm/kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-longhorn
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/helm/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: helm-kyverno
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-metallb
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/helm/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-nvidia
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/helm/nvidia
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-smb
  namespace: flux-system
spec:
  interval: 5m
  path: ./kubernetes/helm/smb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system