apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-external-dns
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-intel
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/intel
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra-nfd
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-kyverno
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/kyverno
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-longhorn
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: infra-kyverno
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-metallb
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-nfd
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/node-feature-discovery
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-postgres
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-smb
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/smb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-traefik
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/infra/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system