apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smb
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: master
    path: kubernetes/infra/storage/smb

  destination:
    server: in-cluster
    namespace: smb

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

  plugin: {}