apiVersion: v1
kind: Secret
metadata:
    name: archisteamfarm
    namespace: archisteamfarm
type: Opaque
stringData:
    steamId: ENC[AES256_GCM,data:iEGXCESYY61d5TMM2MazpuY=,iv:Xpvb2OHLLVwiELP1WlBOSUb5bVb+THQVj8rSnw30NNc=,tag:wCyeSqG27eLzozEdmk0yoA==,type:str]
    ipcPassword: ENC[AES256_GCM,data:Kk5OCyvLnXJ6gOnIm/aW4aC+11grH6qgJxzricsp4kCKr4p+zjG1Z30IHdTM18lh6Lj2BBXURhBLcbY8WpfbUk0B/a+3hpYq95z+XuXrDYc40xTc9RTX3UaRbZoKrFGPqUhPQ8PJsC4bsPe3AH5y4+WVHyXmD3Lm0wxAqNwV0WE=,iv:cGK4fJl+LzsyTMXxYlhM1izEbdHdIN0KmXSosc1hP1Q=,tag:+L/9BkDjHyB7Q4sq8xgh5A==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N0E2TW9ZY2M4YXlkTVpj
            UFBoOWJaU0Q2K0VZRlVVVWNmdUtrQktyU1hJCnFEWWgvMlE0WmxSM2xveTU4WU95
            SjZCZ21RaldjSXorK1pZYVB2bmlMMXMKLS0tIDl0WGQ3NWdSMjdSLzRsMVlQQ1JD
            RDB1Q0VtaFJza0RIQWM4MnVQSUllajQKJmxFORzREsHzoKEVpPOPHD5Cl62Y0JtJ
            j3B1K5fvb1zGmxcird+sLCYiAfN9sfWfrtdidvIC3LkXV6+ClJQwSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ0VxZzZxZGtQdXJJbUd6
            WEVidjUxVnl3Q3lsZFFvUVJheHJpY2FKaEJVCnRkYWJINWxWb1pXL1oyZFpuVE11
            Vk5mMG8yRlJyTUNxaFB6Ujc3UTE3a0UKLS0tIE1DRmpXR0NZV2FYaVZOcWppYndZ
            S0FUWmp4NW9ZMHQyR29rQ1pHcXZSM3MKXUi5nZVN+Q89EkOZRg3+badi6xQZNQHR
            XpYogdnp9uQPmezFU7FTrvUkdMtYOtyutJlnkTfe7MuSZL7a2ALZDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T00:19:28Z"
    mac: ENC[AES256_GCM,data:eUDYeQWYsDsSOsSTWnYl8P6jsh/YQQq3H2dOiTVbTh8dfvAzI83Ls6tmw2sndT/gR8w88+K3vByAQdtJ9EKrDYxuTKQiawU1tByX1YMpGBrcfQVIqIqP3P7XGNPB9okoxkOY6SgzSLJIQgGo+/HdJvef5YgpIW4p1EZ4cfSz/8U=,iv:DKeonByrTxVL0tlqwwZNGmKyUZs+TvJnVfdehlKEGP8=,tag:/s/B0Jl/mGXR/0kuLn7kZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
