apiVersion: v1
kind: Secret
metadata:
    name: archisteamfarm
    namespace: archisteamfarm
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:nFT0pKCvTb2yyPNx+xOt/UCopjY5iI+71Gvpi1IvZT59wUcKKnJGtmaJWGvL9Z7pIKyZdBXcEs+VI1M2ka291m0Ar/XV4zvxyV19kzvI7HTLB/Y27g1hj8UPiqrCwwBfF5Mfvro5PBXet/7gt5eRJW6XprTp2jyHglzjk7XMwOtg0hKQayGURgztZ55m+jCW1Fzp/T5I1wu2wEb6hcQFDX7NVudW7RxAhw+j7/BdNzkSSsdXKgZwLjiegZ7VTiGIdHkhj4G71v9R8TiR+s655YehQ+EBO9neIjJWWg==,iv:HcO/Jr7JMGvYl36gB0AGJpCg4PMZ+b8eQXhmiLhijaM=,tag:i3iE+7ImlpCuVVqM1BNeXg==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N0E2TW9ZY2M4YXlkTVpj
            UFBoOWJaU0Q2K0VZRlVVVWNmdUtrQktyU1hJCnFEWWgvMlE0WmxSM2xveTU4WU95
            SjZCZ21RaldjSXorK1pZYVB2bmlMMXMKLS0tIDl0WGQ3NWdSMjdSLzRsMVlQQ1JD
            RDB1Q0VtaFJza0RIQWM4MnVQSUllajQKJmxFORzREsHzoKEVpPOPHD5Cl62Y0JtJ
            j3B1K5fvb1zGmxcird+sLCYiAfN9sfWfrtdidvIC3LkXV6+ClJQwSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZ0VxZzZxZGtQdXJJbUd6
            WEVidjUxVnl3Q3lsZFFvUVJheHJpY2FKaEJVCnRkYWJINWxWb1pXL1oyZFpuVE11
            Vk5mMG8yRlJyTUNxaFB6Ujc3UTE3a0UKLS0tIE1DRmpXR0NZV2FYaVZOcWppYndZ
            S0FUWmp4NW9ZMHQyR29rQ1pHcXZSM3MKXUi5nZVN+Q89EkOZRg3+badi6xQZNQHR
            XpYogdnp9uQPmezFU7FTrvUkdMtYOtyutJlnkTfe7MuSZL7a2ALZDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T02:55:43Z"
    mac: ENC[AES256_GCM,data:dcHbs5XJ7T3GjZyZfQsxVirEGyXTxc6/oexlBkoCiDdcZvhhwwxAZgPtw5soaIwObgTh+dh/UP6JoIOv5Kdyym5kjurMG4cd7Amdd9ahcWquLtReeSCnfEZzlW8kT40ITLform4YSLS9h9devLbub5MAplyocu5VlgVGdmTAbg4=,iv:/2rkW6xXcowtTDZCrIkO3GU10u+rcnGG2sAVNYZgw0o=,tag:ahSWB4LDG3N87B1+2gLhsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
