apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-gooncraft-reborn-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: minecraft
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 5.2.0
    helm:
      releaseName: gooncraft-reborn
      valuesObject:
        image:
          repository: itzg/minecraft-server
          tag: 2026.7.0-java25-jdk
          pullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 256m
            memory: 1024Mi
          limits:
            cpu: 2
            memory: 6144Mi

        extraEnv:
          INIT_MEMORY: 1024M
          MAX_MEMORY: 5760M

        workloadAsStatefulSet: true
        strategyType: RollingUpdate

        minecraftServer:
          eula: "TRUE"
          version: "26.3"
          type: PURPUR
          difficulty: hard
          whitelist: "Baconing,Kamieo_,Im_Breez"
          ops: "Baconing"
          enableCommandBlock: true
          spawnProtection: -1
          viewDistance: 32
          icon: https://github.com/Baconing/dots/blob/master/kubernetes/home/games/minecraft/gooncraft-reborn/app/icon.png?raw=true

          motd: "gooncraft its back its reborn it totally existed b4"

          modrinth:
            projects:
              # - paper:calcmod # Not 26.3 yet.
              - paper:inventoryrollbackplus
              - paper:journeymap
              - paper:pvp-clumps
            downloadDependencies: required

          pluginUrls:
            - https://hangarcdn.papermc.io/plugins/VanillaChanny/JReiProxyServer/versions/26.3.0/PAPER/jreiproxyserver-26.3.0.jar

        persistence:
          labels:
            recurring-job.longhorn.io/source: enabled
            recurring-job-group.longhorn.io/backup: enabled
          storageClass: longhorn
          dataDir:
            enabled: true
            Size: 16Gi
            accessModes:
              - ReadWriteOnce

        serviceAnnotations:
          mc-router.itzg.me/externalServerName: gooncraft-reborn.minecraft.saturn.ci,gooncraft-reborn.minecraft.local
          external-dns.kubernetes.io/enabled: "true"
          external-dns.kubernetes.io/hostname: gooncraft-reborn.minecraft.saturn.ci
          external-dns.kubernetes.io/target: jupiter.saturn.ci
          external-dns.kubernetes.io/cloudflare-proxied: "false"

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas

  destination:
    name: in-cluster
    namespace: minecraft

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true

  