apiVersion: ENC[AES256_GCM,data:wgc=,iv:X3gGrw8uy7kb5rq8GO7v6Ykltw2KCiNf2feyyXidKV4=,tag:jCrueEImp99LPgx/Lb1hwg==,type:str]
kind: ENC[AES256_GCM,data:tNGC7Ugf,iv:IN15+WgeWg0JA7e4K+eLlabi87odvvPAeTmNJlaJGgg=,tag:4Q2tK6V93tNK9FG0qzPNpg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GJk75RUgc6M7KJjnwnZ3sUpqoBI21w==,iv:sVnqQHT1t+E46LeXjdR3jK4sfDNZphl3ceis0rlqXwk=,tag:ehJR/lmakHMisOS0kaX/JQ==,type:str]
    namespace: ENC[AES256_GCM,data:V9gIV//FVw==,iv:6U20ScuOm4AyoUCQFKuaBC7qTWXKHDX7En27/HRFJPo=,tag:ff3wJ/1da+l09b+21tZvVw==,type:str]
data:
    username: ENC[AES256_GCM,data:wtI7s5BZEHydgH4=,iv:vHOCOBVcafsnhQVXGt2+AZhu5hgYihq2qtCyysUMNPA=,tag:W0XVfFGAQko3WqovN8KYRg==,type:str]
    password: ENC[AES256_GCM,data:sQPRpmVpoz86W6W0itFn+FbDk00=,iv:0np1BtL7hE2La9+E43WttsQ56pOA1QKkQT5lTlWL1nw=,tag:DNA1vFTVOqjznPxOA2o/vA==,type:str]
    domain: ENC[AES256_GCM,data:KbzQ+RwvBvpb,iv:vfUgAbZk/IikOhdRjTvffJgRSg2XuwtmUnQG0UVbeFI=,tag:UergpV1+Tb3wRGfXnOImdA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UWdZNUNuU0tQbjc5YnlC
            NGRoc3FLMis1WjRZeFpBMS9BYTc2dU55bVJrCnlYVzNnQ0RKdGxyRUFNUTR0MHZK
            c0VLTmVVa21zRkxVSzJENHZMVTF2M2MKLS0tIHBDTzY0Q0dXSEFKc3hYNGJFZVRz
            Q0tLNlBOcGNHR2JYZTdOYzJOeThaT3cKxrJdmvoM3iwqN0C7jlJ4sbfz1Wd312tO
            ciACOD7bC4huZby3Borz/eMdVv2N2IzFSradFBAj/1BqeHR946gRbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uj6zl377wwvgysd0hn8n9h9dcvkuvxcu9948jsr5hxvjwcaguu5s8uxk92
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRWJYQzQzZU5KMEJCM21t
            UVFITHdBRnJZZTl0T1ZBWTFyNGNTVmR3Y2dnCkZrendSa1BHNTBOdGU5L3E5eHpZ
            Vm5ueTU5ellEVlBrZ2tpdm4weExoUTgKLS0tIDdRUVM0amQ2aWN2TnBlMVVGMURa
            eFJEZE1kdGVFNjd6Uyt2L3RvMU41ME0K7AeX60qrxB8lp4GXpZRDSW2Uw3H6NSHb
            3PoLXYCEfxFiuukqsexF9M8Gnw4LEETVYBxA51DLSvo/yb8bnFPtJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qyt44szfs9tx7vdqkhlct5kdkl0jvxdryuvk3azhsml8g4zzp5asq7rc53
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOXhuaGtsckd3OGxtTHlB
            U2NIaFdnTDhxa1BYb2VoZHFnK2tuZlBGS2lnCkFNdkR5WFRqcVF2a2ZkNTE4TnBT
            NmprcmNnMWRwRGlxZDBJOWhXMGQ1NlEKLS0tIEUvR2Z5SGZjZ3FtQTQ3VS9iMkFW
            SGVKU2MyWDVROEdQUGxxeUZMSTlmNE0Ks7OOyB405zlT1E6/1aplYVtsfUWsqdg2
            6DOI91r1Iw38/qWPq/CR7suPfei3mZNQgmzpRDAfWkADyz7PVyUSgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1644z52qrljm8f04j6y6zuey26zj0d2w45yvxplh9ez4xkqqjec4qrkk3hd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCL1FpZlEvcDJpK2UyL1gz
            M2dUdE9Tc3h2T2RlSGZRcUxQc2xFOU9iRG5zCm9SempDbU9nV1RqSDNOWkdaTW1T
            V3E1eWlqTmdSbU5lTmdMQXp2Nk16eVkKLS0tIEhDZVRhRkJtZjdTNzZGR1huYUhK
            eEc0bVJJTzBrSDR2NE8zUEE3M1J0bEkKq/y6LWv1lUW3bdGopBt/tC1ewtNN4fIj
            4YKHNobh5LSlvUYAo0DjyRCVnTpBAnAAuEkdVSyfc3lXW7qWeC70KQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18u0mqjat6rnwkwmxa4xsg6z6czjgcx6pzgfphs2u7zzm0lz08d6sn36jp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZHVwYTZGZkxmcGZobDFw
            QzlDdGcyTGMvMzUxYmxUYUNWTUdPUVQ5ZUdnClNkRy95M1JEVEc0NWQwMTExWWhp
            bHlybjF0V0Rxc3hMTkF2U2FUWmFIelUKLS0tIDNtdytOTGRXWlEvQndIZWswVWtY
            clJqV1V1SHFKUDZLZDN6WHM2Nm5UNlUKEg494fSX7xZdcJ7dOOc0ZaApDzWKPjib
            aP8Ojq/8y+b8N9wminp7kU9zclllUraXJ/g0GRYAnE17IaZp3Nx1Uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a5tthmerk79xmdykzyvradm50zjhw5npqeln6knu8jv2ph5n3eaq0xczr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV3NOTU9xMVdWRkVQVVI0
            UVRqcEZZdnRLd0tBQlFmb29kQ01wUlNXL1NVCmdBUlJ5OG55SlFWSGlJY2YvblpQ
            YmFCYmwwWFV1dEkraHFnU3poM2lpNVUKLS0tIEh1MmFNaGNjTjE3L1NKSVlqempH
            NXBnMGRhM3ppN24vcTMreFhZcWR3SW8KS5Z19xRbrhcOWntppt3s+Z7XnTlyuA+K
            4z7wnj9fdcWO+hmC92O+ibzzX+ehKm94cxlmiVeKbQ+myIWHB461NQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fl9vgdt5q8k3vavv9pd7zya6dqcrq3lz4ecc5ucnndn0m67fup4svdglv5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRTZpcDBJRFR1THhnNWFM
            a3JvczExUWtBaUJpMHZvRDlnYlRwaXpKZmtRCmJmcmVPYXNENFBnQXI1VVk3NkxP
            R2s0TktHTkNSMXViOXNCOSt2YzY4cXMKLS0tIFJyZDFuZjdpK1lhVFZsQmJDRkwz
            Qnc4ODZuMWU3V1lyVzc2NkdDVHNPNHcKRSfeWL1W5cFnrVD5ll1ad2lKNUlKln2E
            NTr1vumulkIOKzoUp5XyevPSuXkmBPexGB9VYE6cT3jN3t+Y6Mwn+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T00:53:28Z"
    mac: ENC[AES256_GCM,data:1W0xSY9lWyGH+Ae0rR2lr/2pw0sq/KukGLA/+Hkz8mlXwZ9K7SFy2K4sNMOmnnEhQkQFj2KHNqJhE0CHvlPUWsT2WR5spE0vFkx8qdVibMlUSZgt2RFuI2oH9s8qyeg0tiGF/EDGuPk4YEwCFp8SHfjnWlH6SLpEpe4Jt5SGbto=,iv:pbDJCmhlpxqbTBEETnwFP9xNvEHFSPCvf9vxYd1eU/M=,tag:gn8OQbbX98LI7qNRcUnKfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
