apiVersion: ENC[AES256_GCM,data:wgc=,iv:X3gGrw8uy7kb5rq8GO7v6Ykltw2KCiNf2feyyXidKV4=,tag:jCrueEImp99LPgx/Lb1hwg==,type:str]
kind: ENC[AES256_GCM,data:tNGC7Ugf,iv:IN15+WgeWg0JA7e4K+eLlabi87odvvPAeTmNJlaJGgg=,tag:4Q2tK6V93tNK9FG0qzPNpg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GJk75RUgc6M7KJjnwnZ3sUpqoBI21w==,iv:sVnqQHT1t+E46LeXjdR3jK4sfDNZphl3ceis0rlqXwk=,tag:ehJR/lmakHMisOS0kaX/JQ==,type:str]
    namespace: ENC[AES256_GCM,data:V9gIV//FVw==,iv:6U20ScuOm4AyoUCQFKuaBC7qTWXKHDX7En27/HRFJPo=,tag:ff3wJ/1da+l09b+21tZvVw==,type:str]
data:
    username: ENC[AES256_GCM,data:wtI7s5BZEHydgH4=,iv:vHOCOBVcafsnhQVXGt2+AZhu5hgYihq2qtCyysUMNPA=,tag:W0XVfFGAQko3WqovN8KYRg==,type:str]
    password: ENC[AES256_GCM,data:sQPRpmVpoz86W6W0itFn+FbDk00=,iv:0np1BtL7hE2La9+E43WttsQ56pOA1QKkQT5lTlWL1nw=,tag:DNA1vFTVOqjznPxOA2o/vA==,type:str]
    domain: ENC[AES256_GCM,data:KbzQ+RwvBvpb,iv:vfUgAbZk/IikOhdRjTvffJgRSg2XuwtmUnQG0UVbeFI=,tag:UergpV1+Tb3wRGfXnOImdA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTi9ZamZLaVZVQm8xazJp
            T0h5V2lKWEJCWXNGRlorVWUzVTdWZjIvVEFvCm90eUR1Y1FRWDZVeXZlWkZzRFdh
            OUM5WmxORzlMb0ZlNE42bi9xQmcxbjAKLS0tIDFzbmx1YnhZbTY1Z2RQRDQyTUU3
            L1g2blRHeWRXQkRwdUgwdWFvSXRpcXMKfosfY8cGvTRvoDELHgw9z75uS+DMXQHd
            KlzA4zGLMdYKK6mW1eA4+wzfpbS6LFLysU2hZXGE1ibm8uII/MZiJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fyrjkzn6w84yya2rkg2z2x5lss8q622faeen2wc4ckjnmecl230qh8sfey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRR1ZLeEd5R2dkUFVmVFNy
            QnI2c29uT3ZNU0dheldxdFVyTXJTdjdpcVcwCnFNY0dSYlllRXFnVkdOWC80dGpn
            ckdVOTExTEgzSXRoRUw4c0FDdkZWWGcKLS0tIHFyNW55VGtVaFNwcWFvYmR1MnZJ
            RS9XS2g4N3ZlcTlHNUdJbVdZcUdXeFUKZqAqWsdaRa+appo+DnbV5g1v7zdyNW7v
            oFqgYOqh1ONwN1WyfGVaulQaMxwUbd4YOoaphU1ur+yR3Rfv/7d4iw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uj6zl377wwvgysd0hn8n9h9dcvkuvxcu9948jsr5hxvjwcaguu5s8uxk92
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VUNXbVNlSGVWTFQ4OEpv
            UGxjdENWL01vLy9mY0VFSHcwVmVTckxja3pRCjRwSGJIRHViMTFib2hLQWJSTUdQ
            R241RDNSN1pUeEcwN0V3N2VtbjdSRnMKLS0tIG5DUVJUblY2cHRJOXFMcC9PV0ZB
            RlA5a2phZmVOMVZJRWRGSzEyakRSVVEKab59pJQHlV531lnd/lIIepQKeeCs6Dtv
            2enMtPyLT270piQX/IPR8+z+bqFqmMeHVpbeibqUByA5D31v98llDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qyt44szfs9tx7vdqkhlct5kdkl0jvxdryuvk3azhsml8g4zzp5asq7rc53
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYmR0UzVWWEhQalFVK1Jh
            M2psZEI5cjlwa2NEL3pSOVVQYWMyc0VEL2djCnhCdjluV3dhVFZTeEhvcnUweDd1
            VktwRExTTExGTG1IenlkV0NpQy9hYTAKLS0tIDVuWVBqZnAzeFZlNU9Sc1VaU2J1
            RE4rMlBCZmhRdlB0a09hWW1YQXRNZDgKj3ixzVHjYUewmJ3OMX0SMEnb8rodOFQE
            5wAZ4EJnyqm88oEwO+vedYUk8mdPROQTOAHD/J7kUiLJHoX/FJ2M2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1644z52qrljm8f04j6y6zuey26zj0d2w45yvxplh9ez4xkqqjec4qrkk3hd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvLy8xNEdVdDFIR3duNUJT
            NjJyM2kycFk2SVEwMmpTUXgzTTkyaldxdlNrCmJuWWk3MXpmcWo4a0VOQXdGaERl
            RDJGTkkrYWdPL2NNOUo0TGhkdStwcUkKLS0tIEtIWVNmVjFTSHNjTUlPSDdwZ3U2
            K3hTb2piZzVkOWJ5V2dURlhyOXQ3eHMKPbH36NMmbn5jE3DVsWMJ+7GZdrnUgCKn
            sgjZFIVrorj8eUVNnwGwd1pGFCB/pKDRVr8IOfq5t0MUIM6a6RHRGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18u0mqjat6rnwkwmxa4xsg6z6czjgcx6pzgfphs2u7zzm0lz08d6sn36jp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU3prTThLb05TRTRqM1BL
            V0Y1eFp1SWRMYThFdk5Na3ZOTmNieTlwZlRjCnF3NFQ0dTlqRytaL1p5L3Vmc0pS
            bGpwQ0JRUWhWWldudTQ1NUF5Wkd5Qk0KLS0tIDZKc08yK2JqejhNV2lNdDdYRzFi
            VEltbkhneHNhVEl3cmJ2cm5CWW4yRHcK/maMbTJsLMdV+3aSjknkCKh2SI0htnG6
            HPHlqC1UXOoe7/qsSYIlRBIDJyGBZ8u4rxoyh7vFYfiQbxz3B88tqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a5tthmerk79xmdykzyvradm50zjhw5npqeln6knu8jv2ph5n3eaq0xczr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SlNPWVJ1NlZncThXMVkz
            QkErQjk1bWVwNE5SUEhCR1luT0FTL0hsVlhvCmdEcUJudjlBQ1hzTDZiWU9UUThw
            bk5PeC9Id1ByY2JkLzJNeFdOS3AwbzAKLS0tIE9jWHVLNi9rQ0lCY0xlMTRTTzVX
            djdLZkpRRFBBYVpSYXNVTkdrc3EwNGsK8CpTh4Ebop0SbOt6QOjCAMyQcyVIcz26
            sgA2YerS56xZmxV0AasI22k2QYzsjyE1UxiUqAU4rtx3Wx/+1hHYFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1fl9vgdt5q8k3vavv9pd7zya6dqcrq3lz4ecc5ucnndn0m67fup4svdglv5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU2xlb0RuejAvNnJRbzc4
            UGJhck9EbFN6M2ZlRzNHbml5cDBScU1SMldZCmlVL1dDQUlzUXJTVFdiamxadjZr
            UU00SnV4bElHbWtrdytvb2l4N1Z6YkUKLS0tIHpvOEVLbTB2QzBsVlpEbmM3R3h2
            MTh2a1Rrc21QT29PSXNnQ0tSSVJwWlEKkxxdJydTHIyWpazFwe+tn0laQk7K8yvt
            m1pDqLxkITJOyxn3o1YWXuNX4EM4MtfolMBhQZdi3f7iYlTBctJzeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T00:53:28Z"
    mac: ENC[AES256_GCM,data:1W0xSY9lWyGH+Ae0rR2lr/2pw0sq/KukGLA/+Hkz8mlXwZ9K7SFy2K4sNMOmnnEhQkQFj2KHNqJhE0CHvlPUWsT2WR5spE0vFkx8qdVibMlUSZgt2RFuI2oH9s8qyeg0tiGF/EDGuPk4YEwCFp8SHfjnWlH6SLpEpe4Jt5SGbto=,iv:pbDJCmhlpxqbTBEETnwFP9xNvEHFSPCvf9vxYd1eU/M=,tag:gn8OQbbX98LI7qNRcUnKfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
