oidc.client_secret: fhaRZHtyu3Z_2.HPvEIUAMCnhrrm_AJHh~QrAHhxkRe4C4Yjefss27uxWF.CeOaC5G1qXCtB
oidc.client_secret_digest: $pbkdf2-sha512$310000$xxLRU84IO0/G/rZdauWtBw$KAc30iT4HvE2JwDaJEIph7JtMavAYS2zkt6KTAgF/k8x6EfezAvgrJoYuR1Uz4jzuaXkR.LelcMoy0XdrIentQ
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM08zcFp6TTZXNHAvRmtR
            VEFVRDdQcy9qYVM2R1M2OWxkdHVwQ2laaTMwCmtGQmdScnVnZGlwL3BWeFBvSW16
            eEdTVFYxTXd0L1E1WkozbW9tRTBpelUKLS0tIDAzckI3WThnemorUjB6RDlQVTNp
            OEoyZnMxcmZ4b0FOL05SVjluaVVWY1EK+bOpHP/vyCSC9W2f6mLo0V+ZKzuX9uHG
            UAYumGONdNWBUzl8oZkEGkff1Q0b0DeLRkxsPM/LYGbBgBfeWBQN+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YTVJdmJhaFBNL1diZ0Q4
            UTVGN240VGpwRzNNZTdrc1pQcDlnM2JQdVhjCnllQnVXVnlGaTljSnhYVDRuYk9W
            Z0ZpSnZDRTg3dktnU2p1WDVGOGY5WHcKLS0tIHB1SE1Kdlp5NUxGeEdWb0hyRFM1
            Qy94YVMzRlpkQVJNQ3F6MXQxN3RBMkEKp8Cz0djQo+Rm0+FrRlX7jjD1ouLVrtiU
            4Dar40NLSbH8toZ1ojKoEc8T4qBcAlcIKwF08h9iuFeWRFYHLdN71A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T06:27:44Z"
    mac: ENC[AES256_GCM,data:wZtTNiXTOl89xqKLxX+n1fbAvHmfD1pFpcAoCtMvNUIndBhUyv9LV4y/I+b6SX559O971OAjaz0wSAt1/6zhoBL+eLhjpA3wGyqthqhzd/oiRkia4iTp/+GMYsvbLPOj/HbNunjZ8flkJrEzCKAS/xzAb5+QYm1M3/SjMoLTslQ=,iv:vwnt+k+nIo4sVzbYxfCHiZz3mr4uha+gnnFm5hyaDUM=,tag:PK98Mn02Y5R0omsWKGeBvQ==,type:str]
    version: 3.13.1
