apiVersion: v1
kind: Secret
metadata:
    name: oidc
    namespace: argocd
type: Opaque
stringData:
    oidc.client_id: ENC[AES256_GCM,data:X9L6XFfZn7KnlynzH+Si3IrPMYUpSf4N8XaCxV2XIdcRMxpUq1L9WVJAJR+vpQBnpgjLXyQltWJDG1Meqsi1JCyk947ai4Ut,iv:wMfiSe+1sYQ48LjOKAjzUymtxuH4JywWeiOGd1CWU8g=,tag:us8b+m0++BlKscljZUfmGQ==,type:str]
    oidc.cli.client_id: ENC[AES256_GCM,data:pQ79gWIJq7jgmpwrXHtHCw9ye5MGnC2RrEgPPnnn59+M3wS8MC0+D5Dwkp4J9bDeyl2rel3V/fjmMyR/5hva9vZdyhYFAjY+,iv:GZCHzxJlgcQ10cNUMxuthAj0M6MO34mzvNgxGOoop3M=,tag:6FRgZCzJMPlQ5H+Q9dxwFw==,type:str]
    oidc.client_secret: ENC[AES256_GCM,data:AGNHpOuieDuO3TXZaWMneul4P6qG1JttQbj/syfAYCkwPUQeLWglmKymWSSTbaVkO7ZEmHl4Q7CIhhTHZTjavfj9JjpgBpAA,iv:yCqmzCRTT6ubrFH0nGcBjFoXk/cyHK7G1mEbz99mDFw=,tag:A7o8E7x0rpvfZnpkWXzGkQ==,type:str]
    oidc.client_secret_digest: ENC[AES256_GCM,data:qFrnFP5aJtkH548uAqC1Y0jL+jbe1YyNiO5Qq/ET+6jwlOtuzppyGcO7sh6sSn7RsVCmWjMSmaxJ1E3q3NgmcsEd0gEcD3oXcPoKJKZtbol/91oyCpanTU1lCGlV8SwAwCX2k63fdlGIxuNncfLrNr3x0tX/5mkQr6bChdlVYqCAYMc=,iv:IGSzGKt9x81PLrEjvKclCt4G8OqMf8ujqxrQiXr2XN4=,tag:bG98kKRHBByJiWcd9q69WA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM08zcFp6TTZXNHAvRmtR
            VEFVRDdQcy9qYVM2R1M2OWxkdHVwQ2laaTMwCmtGQmdScnVnZGlwL3BWeFBvSW16
            eEdTVFYxTXd0L1E1WkozbW9tRTBpelUKLS0tIDAzckI3WThnemorUjB6RDlQVTNp
            OEoyZnMxcmZ4b0FOL05SVjluaVVWY1EK+bOpHP/vyCSC9W2f6mLo0V+ZKzuX9uHG
            UAYumGONdNWBUzl8oZkEGkff1Q0b0DeLRkxsPM/LYGbBgBfeWBQN+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YTVJdmJhaFBNL1diZ0Q4
            UTVGN240VGpwRzNNZTdrc1pQcDlnM2JQdVhjCnllQnVXVnlGaTljSnhYVDRuYk9W
            Z0ZpSnZDRTg3dktnU2p1WDVGOGY5WHcKLS0tIHB1SE1Kdlp5NUxGeEdWb0hyRFM1
            Qy94YVMzRlpkQVJNQ3F6MXQxN3RBMkEKp8Cz0djQo+Rm0+FrRlX7jjD1ouLVrtiU
            4Dar40NLSbH8toZ1ojKoEc8T4qBcAlcIKwF08h9iuFeWRFYHLdN71A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T11:32:29Z"
    mac: ENC[AES256_GCM,data:2a6Vc+h8jvOMxXHCJ9FpHNkPEs2kuzCfDBWHBg/K24UaPLjjZtxPIctVzfnzzzYzU7LMNPbVvKz2E3zXUsGJIE7JG0dTvCK3fSHSFqeyho4n4hg2SoZfi5lb1SvwmD2OJ8JxE+SzV/MRNa2sVvER/1ibZ5NaAqgKitQIxE5EN+I=,iv:vG7dgs0sNFhGgxhwVoEhLARk65QEVwrI5EXMjYRsajM=,tag:FvynEhfOUGgpx88ye9vr/g==,type:str]
    version: 3.13.1
