apiVersion: v1
kind: Secret
metadata:
    name: oidc
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    oidc.client_secret: ENC[AES256_GCM,data:AGNHpOuieDuO3TXZaWMneul4P6qG1JttQbj/syfAYCkwPUQeLWglmKymWSSTbaVkO7ZEmHl4Q7CIhhTHZTjavfj9JjpgBpAA,iv:yCqmzCRTT6ubrFH0nGcBjFoXk/cyHK7G1mEbz99mDFw=,tag:A7o8E7x0rpvfZnpkWXzGkQ==,type:str]
    oidc.client_secret_digest: ENC[AES256_GCM,data:qFrnFP5aJtkH548uAqC1Y0jL+jbe1YyNiO5Qq/ET+6jwlOtuzppyGcO7sh6sSn7RsVCmWjMSmaxJ1E3q3NgmcsEd0gEcD3oXcPoKJKZtbol/91oyCpanTU1lCGlV8SwAwCX2k63fdlGIxuNncfLrNr3x0tX/5mkQr6bChdlVYqCAYMc=,iv:IGSzGKt9x81PLrEjvKclCt4G8OqMf8ujqxrQiXr2XN4=,tag:bG98kKRHBByJiWcd9q69WA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM08zcFp6TTZXNHAvRmtR
            VEFVRDdQcy9qYVM2R1M2OWxkdHVwQ2laaTMwCmtGQmdScnVnZGlwL3BWeFBvSW16
            eEdTVFYxTXd0L1E1WkozbW9tRTBpelUKLS0tIDAzckI3WThnemorUjB6RDlQVTNp
            OEoyZnMxcmZ4b0FOL05SVjluaVVWY1EK+bOpHP/vyCSC9W2f6mLo0V+ZKzuX9uHG
            UAYumGONdNWBUzl8oZkEGkff1Q0b0DeLRkxsPM/LYGbBgBfeWBQN+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YTVJdmJhaFBNL1diZ0Q4
            UTVGN240VGpwRzNNZTdrc1pQcDlnM2JQdVhjCnllQnVXVnlGaTljSnhYVDRuYk9W
            Z0ZpSnZDRTg3dktnU2p1WDVGOGY5WHcKLS0tIHB1SE1Kdlp5NUxGeEdWb0hyRFM1
            Qy94YVMzRlpkQVJNQ3F6MXQxN3RBMkEKp8Cz0djQo+Rm0+FrRlX7jjD1ouLVrtiU
            4Dar40NLSbH8toZ1ojKoEc8T4qBcAlcIKwF08h9iuFeWRFYHLdN71A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T11:46:53Z"
    mac: ENC[AES256_GCM,data:TzgYbYkFi24OaJuQBvzZ1CbCZyTnfvhARn674GIIKd+BH0V4CAkR64wKrEXjkpfW4VL2dZ/bBY9c+2bFOzE3rTGYN0AP7wiciD6099URsYR7VhOh1UMFQYTLxjK7UHPl4ozlxk/k92rwf+s5PIeGYXD0SjWUsktfh5ZzVOCpGow=,iv:gVWsanc/GNz3ibgoNoh9pnOiZS1rzpLUbWqU48hKHqE=,tag:hETeznrpKwNnqNcRsb5czg==,type:str]
    version: 3.13.1
