apiVersion: v1
kind: ConfigMap
metadata:
  name: sops-cmp
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: sops
    spec:
      discover:
        find:
          command:
            - sh
            - -c
            - |
              find . -name '*.secret.yaml' | grep .
      generate:
        command:
          - sh
          - -c
          - |
            find . -name '*.secret.yaml' -exec sops --decrypt --in-place {} \;

            if [ -f kustomization.yaml ]; then
              kustomize build .
            else
              find . -name '*.yaml' -print0 | xargs -0 cat
            fi