apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slskd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: master
    path: kubernetes/home/media/slskd/app

  destination:
    name: in-cluster
    namespace: media

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
    automated:
      prune: true
      selfHeal: true

  