apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kaylaatm10lite
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: 5.1.3
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2026.7.0-java21-jdk
      pullPolicy: IfNotPresent

    resources:
      requests:
        cpu: 1
        memory: 2048Mi
      limits:
        cpu: 4
        memory: 8192Mi

    extraEnv:
      INIT_MEMORY: 2048M
      MAX_MEMORY: 8192M

    envFrom:
      - secretRef:
          name: curseforge-api-token

    livenessProbe:
      initialDelaySeconds: 300 # 5 minutes

    readynessProbe:
      initialDelaySeconds: 300 # 5 minutes

    workloadAsStatefulSet: true
    strategyType: OnDelete

    minecraftServer:
      eula: "TRUE"
      type: AUTO_CURSEFORGE
      difficulty: easy
      whitelist: "Baconing,TickleKnees"
      ops: "Baconing"
      enableCommandBlock: true
      spawnProtection: -1
      renderDistance: 32

      motd: "i love you so os sososo so soso so sos o much meow"

      autoCurseForge:
        apiKey:
          existingSecret: curseforge-api-token
        slug: all-the-mods-10-lite
        fileId: "7420356"
        includeMods:
          - living-things

    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
        Size: 16Gi
        accessModes:
          - ReadWriteOnce

    serviceAnnotations:
      mc-router.itzg.me/externalServerName: kaylaatm10lite.saturn.ci,kaylaatm10lite.local
      external-dns.alpha.kubernetes.io/enabled: "true"
      external-dns.alpha.kubernetes.io/hostname: kaylaatm10lite.saturn.ci
      external-dns.alpha.kubernetes.io/target: direct.saturn.ci
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"