Version: v1
kind: Secret
metadata:
    name: postgres-superuser
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:DQH8gq0=,iv:4885qp7QQ5neRAoefFSBQfBzrEAn+32cFZ+OVmznByQ=,tag:y/1USS9OdL15zPzwXXiXfQ==,type:str]
    password: ENC[AES256_GCM,data:81b9wW5oWlaCONDjT4O7k1W7M1RZosSYbf9SAcFZsw8=,iv:fWeulfZwesADfCyUNnXwzKI4aQ+ORc6cGgmJNn3Fjow=,tag:ORQlh8X1pL5n68bqFO0dsw==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb1laNm9KU2lrUEQxcWFH
            N3Z1aHhUMExjSlhxTVpnRzZQZjc2NTV3bzA4CkNaUEVaeE92TDZhVllBYWQrQ2gx
            eE9XVC85NlMyZnZyenB2SjFBbUpxcTQKLS0tIGVveTVIQWozanlOMEpjZVR3NStE
            VUxKckRyZ0FnTDA3QXRSbFhuQ01Pc1kKU5oCPyS1fYQB7w3EabonQunsKChdeFdi
            QYgJWoorL1Sp/TcvqaYMOoCFtGYyV/2Ok6ArknlfuTfxuEt6Vlznnw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cG1wYTIrd1pyVTloeisr
            UDZKQ0Q0RjdqT05HdzZKSHVpQ2tHMHVtN1dBCjBvTVorTVpyRlBQb042NlpES0Fv
            MHFNNEM0cVAzNXNoR0hUdUJuT1NOdzQKLS0tIEFBZVZZdnFpRWVmbERVU0ErOXQx
            RGFQNFJGZlhxbXl6ZHdMZEZrSWtBZTQK5l/A58foFbJISf3UoQibymaqLk4c3TkI
            y6ysK0pW5awQltiz3DQggcuQDTHIzLNi5eELr3bhdUa4plq/o264Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T01:05:00Z"
    mac: ENC[AES256_GCM,data:Cg4P9DaVscm41/mJ+/EKx6i3zLFqKVaQB50acZ5yT+w5rAYSO6Fnv7n0QdCHj6bcAIQDjK0dHSFZFQ0FaKm/jCR+N8FhpHot4GsU7RgK6ZSHxPG1YDQykch31Nd1nL6xRwzhJF+GRHwS+yJijDr0OW9491CdmtyT9jjRzxI+MTA=,iv:LG/2+2yUZ5Y/TivWc2IyXCBE+KfTND9Jgmhl3UynQU8=,tag:ZtWR1aTpjpGwHMpf9i6ghA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
