apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:DQH8gq0=,iv:4885qp7QQ5neRAoefFSBQfBzrEAn+32cFZ+OVmznByQ=,tag:y/1USS9OdL15zPzwXXiXfQ==,type:str]
    password: ENC[AES256_GCM,data:81b9wW5oWlaCONDjT4O7k1W7M1RZosSYbf9SAcFZsw8=,iv:fWeulfZwesADfCyUNnXwzKI4aQ+ORc6cGgmJNn3Fjow=,tag:ORQlh8X1pL5n68bqFO0dsw==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb1laNm9KU2lrUEQxcWFH
            N3Z1aHhUMExjSlhxTVpnRzZQZjc2NTV3bzA4CkNaUEVaeE92TDZhVllBYWQrQ2gx
            eE9XVC85NlMyZnZyenB2SjFBbUpxcTQKLS0tIGVveTVIQWozanlOMEpjZVR3NStE
            VUxKckRyZ0FnTDA3QXRSbFhuQ01Pc1kKU5oCPyS1fYQB7w3EabonQunsKChdeFdi
            QYgJWoorL1Sp/TcvqaYMOoCFtGYyV/2Ok6ArknlfuTfxuEt6Vlznnw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cG1wYTIrd1pyVTloeisr
            UDZKQ0Q0RjdqT05HdzZKSHVpQ2tHMHVtN1dBCjBvTVorTVpyRlBQb042NlpES0Fv
            MHFNNEM0cVAzNXNoR0hUdUJuT1NOdzQKLS0tIEFBZVZZdnFpRWVmbERVU0ErOXQx
            RGFQNFJGZlhxbXl6ZHdMZEZrSWtBZTQK5l/A58foFbJISf3UoQibymaqLk4c3TkI
            y6ysK0pW5awQltiz3DQggcuQDTHIzLNi5eELr3bhdUa4plq/o264Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T02:00:33Z"
    mac: ENC[AES256_GCM,data:eMcL11v7eMt29R5Yg5tOjEQVExNULvsO6FwCY63NZkbTnPrGHIj2/VejFMgAC4vJKg1qtuOtoZQBRf5DqphC72QsNRTcg9poeo/wuSQWTH/1s88+wT2l36cazkdMUQ6qmshIDcZiaralAZ97WSfa6se7eDx1OY1eu9ahw2E9ITo=,iv:1ZPGfLCQyL3+n2FkIqgPHCN+FxYDNWyqxbKoMbrTdLg=,tag:V6JLUfy6qvrGG1d4tT+sFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
