apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cross-seed/app.yaml
  - ../jellyfin/app.yaml
  - ../navidrome/app.yaml
  - ../qbittorrent/app.yaml
  - ../servarr/app.yaml
  - ../slskd/app.yaml
  - ../smb/app.yaml