# TODO:

# valuesFrom:
#   - kind: Secret
#     name: postgres-superuser
#     valuesKey: password
#     targetPath: serverDefinitions.servers.main.Password

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: pgadmin4
    repoURL: https://helm.runix.net/
    targetRevision: 1.66.0
    helm:
      releaseName: pgadmin4
      valuesObject:
        image:
          registry: docker.io
          repository: dpage/pgadmin4
          tag: 9.17

        # serverDefinitions:
        #   enabled: true
        #   resourceType: Secret
        #   servers:
        #     main:
        #       Name: Main
        #       Group: Servers
        #       Username: postgres
        #       Host: postgres-rw
        #       Port: 5432
        #       MaintenanceDB: postgres
        #       SSLMode: prefer

        extraConfigmapMounts:
          - name: pgadmin-config
            configMap: pgadmin-config
            mountPath: /pgadmin4/config_distro.py
            subPath: config_distro.py
            readOnly: true

        extraSecretMounts:
          - name: oidc-secret
            secret: oidc-pgadmin
            mountPath: /var/secrets/oidc
            readOnly: true
        
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
        
        autoscaling:
          enabled: true
          minReplicas: 1 # todo: 2
          maxReplicas: 3

        commonLabels:
          recurring-job-group.longhorn.io/backup: enabled # persistentVolume.labels doesn't exist.

        persistentVolume:            
          enabled: true
          size: 1Gi
          storageClass: longhorn
        
        VolumePermissions:
          enabled: true
        
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.tls: "true"
            external-dns.alpha.kubernetes.io/enabled: "true"
            external-dns.alpha.kubernetes.io/hostname: pgadmin.saturn.ci
            external-dns.alpha.kubernetes.io/target: direct.saturn.ci
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: pgAdmin
            gethomepage.dev/group: Database
            gethomepage.dev/icon: pgadmin
          hosts:
            - host: "pgadmin.saturn.ci"
              paths:
                - path: "/"
                  pathType: Prefix
          tls:
            - secretName: "pgadmin.saturn.ci"
              hosts:
                - "pgadmin.saturn.ci"

  destination:
    name: in-cluster
    namespace: database

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
    automated:
      prune: true
      selfHeal: true

  
