piVersion: v1
kind: Secret
metadata:
    name: oidc-pgadmin
    namespace: database
type: Opaque
stringData:
    oidc.client_secret: null
    oidc.client_secret_digest: null
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RWY2a09GaDlBOU50WDFG
            TFhNSjZRaHNQS280c2xuUzdZUGJYVnRvcHc0CnoxRjFMUzJGeEFBbENjd3dkY0Na
            Y0pHSFRVR1pKcVZVMHlBbWVHdDdoS1EKLS0tIFMwT3BCMTF6Y2pZRGhaWmxjdVhM
            NTJLaEJTcHhCK1NOK1JtSGlqTThpd3cKPI4v/Ug20PJ8qrqyeeHADFAVuLnre9DM
            FIMWX7PRKnt6WPVifxtcPtX1I7ixrOaIL1qHiL3RfSu6rOq1IMyCbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcVBKRWQ4VHUrWHFkZXB4
            cUgzYnBDYVYrRS9sZzg2a3BkVHNIT05aVm5zCmxwZzFIWGFBcTUxYmkxZG1CdnVw
            RXNjTDVlcHFodGNhV0xoSHV4SWVjaXMKLS0tIDNKQkZFOS9HYjJJNUhQZFAvem1t
            V043Z0Y1R2RvY3FFeEtZSlJXTkoyNDgKgppm0b7Fi0hW5Qd7ts3oNIxc2X9OrW6G
            PR/xsjvHrz+G/+2qnilYJGg5tcStKxhs+MvZ/bePOoBl6wD4SBI6ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T05:30:31Z"
    mac: ENC[AES256_GCM,data:v/jGJXCxknPymObuLT/yYz4VQrM4YAk+8Ybb/kmmWfOfAurglFYc1yrk9TyGHQs0DZHKk6nH3NXVntWsvyzwz47Tu2oFtNhtuoYvEM++0zCsJCgXGivym4imBLLjAIvIL5APFsH8SJAEMR23Lnoi/tPrm3MA4phIHt2cvUj/YLA=,iv:dRkDJoJEWEkGQDm7V2sZpdkUWhjnDcW5geuKrFzh5Lc=,tag:PKgAOy5PiGAmlDmGUi8SUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
