apiVersion: v1
kind: Secret
metadata:
    name: oidc-pgadmin
    namespace: database
type: Opaque
stringData:
    oidc.client_secret: ENC[AES256_GCM,data:y8uQ4+Dmwxve5I/Rxipzra4yNwqbvuVe+nBqXhZ4xSwg8porciqLBH2TG7MIunz8bSBBUAZe54TyWmKD//2VnTyyfmkErbJX,iv:CutJtC0gXfS0lP4MzSUxlTQ4cabPTB2HklsdFA+wpcE=,tag:DYflqO/a7PZH5lfJNBf5TA==,type:str]
    oidc.client_secret_digest: ENC[AES256_GCM,data:m4ydu5PbFKCyW6KKGanySkJqTNyJl8p4TnKMbh9OqeI0w8KaB82fSJ0Fb2NiG+Q2mJ01SEHG7IJP/Vvlp0ms1uCV6jwuekowBVeBoYfRRE9Za+yKMBZ8ko0AEx5k1BIySaNE/5otBN2bIo5hKDqhGhH1v3A1xDB/vssbBILgQK8kSc8=,iv:AuSHQmVLwdfkGVAxxAZRcS17psXl6h8NGVRBo2QQ4zg=,tag:GS3sZ9HUaN3ayfJuVakH8A==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RWY2a09GaDlBOU50WDFG
            TFhNSjZRaHNQS280c2xuUzdZUGJYVnRvcHc0CnoxRjFMUzJGeEFBbENjd3dkY0Na
            Y0pHSFRVR1pKcVZVMHlBbWVHdDdoS1EKLS0tIFMwT3BCMTF6Y2pZRGhaWmxjdVhM
            NTJLaEJTcHhCK1NOK1JtSGlqTThpd3cKPI4v/Ug20PJ8qrqyeeHADFAVuLnre9DM
            FIMWX7PRKnt6WPVifxtcPtX1I7ixrOaIL1qHiL3RfSu6rOq1IMyCbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcVBKRWQ4VHUrWHFkZXB4
            cUgzYnBDYVYrRS9sZzg2a3BkVHNIT05aVm5zCmxwZzFIWGFBcTUxYmkxZG1CdnVw
            RXNjTDVlcHFodGNhV0xoSHV4SWVjaXMKLS0tIDNKQkZFOS9HYjJJNUhQZFAvem1t
            V043Z0Y1R2RvY3FFeEtZSlJXTkoyNDgKgppm0b7Fi0hW5Qd7ts3oNIxc2X9OrW6G
            PR/xsjvHrz+G/+2qnilYJGg5tcStKxhs+MvZ/bePOoBl6wD4SBI6ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T06:31:17Z"
    mac: ENC[AES256_GCM,data:TmTsUq8VQqV8WVLERqatvBZsGZk9/07hGs0pCurZISSG7vRDIXRzKkqUDDbMNobnB6WWhsm0d4ha+aqaaExEqyQMUc+nE3rfVYXfh/Umh5SIKv+CYebiVnKQYOs+I/TWPXuQvANFl/EqOyKG2BNES3hz8KzTOEzQwsA1N685p7M=,iv:E4Zr8xuVgfKyIUD7s5J9hAxWihzoGtiaz73WkoaoJIE=,tag:/DOkwPavHIyMNukFbINqqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
