apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
stringData:
    adminToken: ENC[AES256_GCM,data:wI0eIVqQMwetJDqszYGFWoenFg4dnAaTDOiirPXm9HcBYKhv3oG8IYCsuW96AprE9AAHp3RVeJiqOyuS0+VVv+UbvhDw6HBLV6pTTkfT/R9v9Bchrln2tFBYK7vgm2sYra+ucJ53buKw2b865w3EOshRIYHW+1Oh1aKtsIL0Bo8=,iv:+y8rHiI1/juNGd3iCg2XIIVk95c+3XJ1uGBCsLGwrzE=,tag:hMk9xEW2FZkf4i22xUFHuQ==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNE1ZUUQ1eDhBVGttTHlB
            TmpMMnVjKy9wb0dVZWI1MEZ0Q2lUVGdEVmx3ClVPcjZxQVczTmkzNjI2TlNIa0pZ
            enQxUlhSeGlUZS90dkUxWVZHK09ZMEUKLS0tIEVMUGtITGVrWVQ0RGZvaENVeVJ2
            djFZU1M5Y013Y05PbXozUS9jRTRkVUEK2NHP9wKFiZMmAbwuVGbrfeK73zs40WBs
            JExBu3QVyrh5go8cUORfM4catZsSdHg9TV9Omv6E6xrsJDVo4BINpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMVVvc1kydDZ5WDE5Nm9y
            Q0t1SkVuQ0xhY3FXUEJEa1Rmd1ZxV1ZRNFZnClF5QmdMQ0YvUE14bW9DYlAvSUlY
            MGFSRE9UaS9IdW8vZ1QzZmZTYVIrNzAKLS0tIEVPMDAzdEtDbnZqNTZkbXdsQWtF
            ZFF2VUpQTzRlaHZWR1NjMDl2ZUZvY0kKaLDoActDFU8KkuyGckyDW26tTg9LQ16f
            6KZeh8xPfhcdBlNRyD9JSExhruYhz2fX/lIru9JPTVc/elxaZ/U5IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T23:50:10Z"
    mac: ENC[AES256_GCM,data:zTPYH/dhv0aS8raRpH9YASi7q8mzn3IXXRiLNrpJLNTTrwjGrohS4MKfD6tlgTNGv6HRx577/djIjnkUW3eKz/ebPoi9k8zdwEHsCxWuaewzgLQlEGFmiUFUwePl2xeFd+3CeCTLVDfaqqIs1QTRHTpMhFcxdVSymMMQvSZNrds=,iv:9r8VbGW0xpxzG/rwjPUndKffc1JxRUdC+bvzHK0G6p8=,tag:m1W/PiYQ6Lo/xEh17RnJRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
