apiVersion: v1
kind: Secret
metadata:
    name: homepage-widget
    namespace: homepage
type: Opaque
stringData:
    HOMEPAGE_VAR_AUTOBRR_API_KEY: ENC[AES256_GCM,data:ckhEtfjzPnTqMwx0d0IaibGYzXEsF8z3Gvs92kgNJ28=,iv:ZxjfTqc2Oitfr7u72jlTxdPH3HAeyVAPU2T5UAsL5ZA=,tag:ezJfxRGbplk2CQUkcMJFEw==,type:str]
    HOMEPAGE_VAR_BAZARR_API_KEY: ENC[AES256_GCM,data:r86XgtRvTu+6c8v1jiBXu8gfR4i78mw+BkhzocrEf00=,iv:FQ4VUpX1WxsNwzDr+R+SnaWN6t8r4oZkWbuz00p0uas=,tag:6SmShVs7vt5z+uN3VQHubA==,type:str]
    HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:ZgBLg/3CM3vKriq3+oBpi8Vby977w+hpH7uSMouz/4A=,iv:9wqvGbmY/U5605uMNobjUqAXAjkpNE9czwqlN8WmrPs=,tag:7GqselIZiCR+tO2IC/FYtA==,type:str]
    HOMEPAGE_VAR_LIDARR_API_KEY: ENC[AES256_GCM,data:Dhfep8t40Z9tT5b9DfKR5ErBNBcXF6/qXhYK58Rvn8o=,iv:doGyteBryPg4eWyCcNpheU6mkIjmyIdhasS6a2ClurY=,tag:zwH13q+WtDE02w/ekM/dfw==,type:str]
    HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:q2z69vzaLGguNLNNG9ZVOGmj5ENTYA9wrxtbRChFs24=,iv:5qHVLCnJ1dduFFq0N+5MwLwtSQA72SKATlx+z1JZ/L4=,tag:BNmCN2t6Dv3/rzbibc+yMA==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:Ei8SXRA=,iv:mosnzYLbBMbqPc1UC6xHkNUymLbt8Da2VyHrBk+pxYo=,tag:vYugjm4a9dUKWG5wDzeKVw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:8PtD7nHYckULEjTCWVoOTEuU8S+gmGAa+rx2BwunHXA/eSVdzph8qfo/bvoM5k9Y2g+Qg+3XoFo1+8hkDd9I+zZb3bDRgA5tYgPmGO7XaTkthQIghJ8UnYMeKDhCYs7JcjCL71UHvMQkJMdRfEMjmfb+uIzIdZKQ/VaFTYQEZ/U=,iv:c6n3fp9BC4g1V1uRRyT8qktKyU6xvBM9wSqPlQUq6us=,tag:ROi57lZlBJQcTyxjT9FQng==,type:str]
    HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:McUflriwF4HlD5XGw9jAL+iRu6HDHLkym4jcV6uMzp8=,iv:Yy8s3eCW+Gmn1FSFqxZV9O5mBaD0lQjEQjLfTpZAogs=,tag:WvQTqxHPY8+OLumrCeL28Q==,type:str]
    HOMEPAGE_VAR_SEERR_API_KEY: ENC[AES256_GCM,data:T66aQVL4sv5UvtQlj6fB6lTKGmmkWySoYc+37VbhakVUNn/KsLCdMnFOs5AnFOhHOudFr3AuzIxpJ65HyjifOkm/5HI=,iv:zxBB0g/7GHxNOkh8yo/9UWOpyx+LE2lZ9IKXOgKuviU=,tag:29yPca+9chTlcwIw2Q2BIg==,type:str]
    HOMEPAGE_VAR_SLSKD_API_KEY: ENC[AES256_GCM,data:zfcVFByOdfDAvg+Sflex9VuHbgygM2lhkf5GdFTm+o4WxVWlz+nQl3FQnuAww3HMioYuFSvZnh0BBd5yINoXE0kxL4hS7jxLbYxmNUOPm/gFNFbCTjjODj5ULyqbVA+maiBzB4MHusm6S8oIAI8XwNXM/U5mjIoXFbVfIfuxssk=,iv:muFc0k+KOQJs/uhPEs2w94XuF/7eSFiF28NArngA4/s=,tag:NCXDc07v+4ijMedeXacbTg==,type:str]
    HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:R4pzEibiQEBI2XWeKealUJrSWtGHQ4Ma2FMXQv/tPRs=,iv:kjQrp9qIUxZvMiDxOBQOHzDsFiiOIllwjwBBJpPkHjU=,tag:FtHI/FTFG+hkiAdxH3e2bQ==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR2FxTUZNZHBsMjExRllj
            WVlpWC9NdVNOZ0hoOE1NU1llRCt4OWhlZWhnClIybldJNDFzekY2MEF1L3V0VE91
            eEN5SEw4L2NtaVJhamdkMkhYNVJwRm8KLS0tIHE5MkdUZCthSkliUTV4eHd5aXhY
            R1BGa1kwdjBRKzM3UjJBRXd0akJYTk0KlAwWaKUPesLw7RBoOEGpdWIa3+eH88Up
            TkWZy96NqC59PWkwwgSDptnDuPZWhCSGJDpxFSXMlZ7KgIthjfVlMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybzNCZzhxMWJPNWpjQnJP
            WThSSkROUXFzSzNZVjcvcTJnbmtyMVFrOVFzCm5icmlab2tzMHcwRTdSdTlmTEs4
            cmxpZGI1NllBYmRRcFRERFRGMGw0VmsKLS0tIGI5UHFmZG1rWWtQb2w1R0ROWi8z
            alhaRm5wNEVPOFRnNXQ4clJHT0pSUHMKUDVQ6Ag3dePKhbjE9lhfUF6Bb30vzeSl
            bRSEbjEsuU5PldqJCQpFqpdnsxajtMcl8/mMcsA0N6FvuyuvoGiOGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T20:51:00Z"
    mac: ENC[AES256_GCM,data:Kj3zGYbAO9vHtc1Lsd6z914lIEAZBwzAJEBq75irZ4PP8AD2nNknpnPcHLwWcdJSxpjWlug2RMybeCCetx4JIBq7BPeVwEjx2Io9oienZE0XVSlTo5GbI4BAFQLd0GQwSpofkF2jADTXqkCreB37PrF93dfOmWJmbkwhljk/KBQ=,iv:zLDHkroC1LQq3iFfgWt/F7l0qOQJX6QhHEid9eR8In8=,tag:6J7jkQzPCgCcuQ8bcG6AoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
