apiVersion: v1
kind: Secret
metadata:
    name: homepage-widget
    namespace: homepage
type: Opaque
stringData:
    AUTOBRR_API_KEY: ENC[AES256_GCM,data:ka70zlR03XdWT2Wp/GYmfeQk15NtnRIUjwqkyWvnqXE=,iv:EU9MyNQm7a4WMWwLsOA0yoU1YH3u42fyN0ge3eEiV40=,tag:rP2/oWXVRTRdHqu3G4CnQw==,type:str]
    BAZARR_API_KEY: ENC[AES256_GCM,data:iol6vA++aCR/xdKMEC3ZUvaEobI2GblLoxsXlK9pxus=,iv:i839jrhnaQP899WgYfDfzLY6YWH9C7R+o/oR227hBL8=,tag:LSf/rQ7IH5mpH67Ud5YJBA==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:5Z6OcvOehKPABKx0MFKDCFUAPuQLLgGNXvQJTFQQUxg=,iv:PA6fVPdO6w+X2kFEfNiNArlIgouNy3FZfM1LuDV0Cx8=,tag:o5eg+2tQR6Do1xFKuUz9kg==,type:str]
    LIDARR_API_KEY: ENC[AES256_GCM,data:sfbYeDczMohhgp/0pbs2UZYVCgOGWwTG9z9QtJMQydI=,iv:VsYLAsaisl/htHyrCWuAYiJRa03KsXHJms3ScmTVGl4=,tag:5qVwhDP2HpqRu+8Olo2ghQ==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:j82oBAvgHpo7urbal4mQl9tq8IEU5Z1n64XTxH0LgiY=,iv:oc4avo2Bwvmz1HrPD0izGJpWV/ACR8D73PPURcI1G7Y=,tag:s7YyVj21vTlxZYbhVocmqw==,type:str]
    QBITTORRENT_USERNAME: ENC[AES256_GCM,data:zX/90ig=,iv:Y5GVSo5B/WtE0CCPPxb+/hL6kQFNGIRZ9cdZKd2hfu4=,tag:b1/Rcxg1JeChj4X0anTHUQ==,type:str]
    QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:xgxWv7rkH4PmfVu5FSC8l6sfr4GEzfrhEnEr17QMNEmZyGmQup/PmgtuJS+ZeS9B8bfNkKBUi593jrd+RHJbaRZJ5bE/8xokXTuNA5kICCgQjGYW/jX8yqJHAaH+DCeER96H+W7X0+ehwVBYGMWgmf558C/DdPbxpsSKoI5WI5k=,iv:k9+03GJY519Hv40SlkI2xrEeMzQBxiSpes+9ipMr23Y=,tag:JK159UIeejHtY7bCGb3Gog==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:SKOYML1yo3x9XhCPbM6PEVG1iG9jh96KsxaYf5PRQHA=,iv:ussRJn0bISk4aX5OXp2Os9D5GcguPMuZm7Bs90NhW1g=,tag:2sCcPSxaLSkrzECri/7wtg==,type:str]
    SEERR_API_KEY: ENC[AES256_GCM,data:sdQjeMaDCgMoZ68TT5Z0DFtbg/7et5psFexykGa40V6sPSwWkz++8n5EQN9b3fq+pJ3EvZQoxKgLoS8PPqxzQMazRaQ=,iv:+n7xcpbYU1zfXoUzNktRfs5dtCs5xdE7E2lKexteCbA=,tag:GGLq9QkGfavbltXlRdAQFQ==,type:str]
    SLSKD_API_KEY: ENC[AES256_GCM,data:mIULoQscC9GnSQL6XWIYe5/LHtvKvN+sRTbYAy+pdD8Znm4uGXmMWkUCInyuQYEQGRjSaROH3kDvSdpbWDSYULEb9l0UH4IiedkpipLTxhnsxpwnTypb6uhdWW6VoDUv/JlMdE9qTSoCo51y44uCePmdcRI6dnRXR/kgDhvEqFs=,iv:JT/aXlad8+tsbZV3zKSd4ap7EnyfzVh2RSmohlDW96w=,tag:p+hNZt2Hyqu+RWEPD9sMiA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:uBfJKitq+usBGdVNUjojI0JaYEP+a5TTkrYWrVYDiRs=,iv:igAkei6h4cBwso9LoHAfKFpilPhnGuhA1MHVLS8ubkY=,tag:OKVr720EUqkKHUPl3IG2DQ==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR2FxTUZNZHBsMjExRllj
            WVlpWC9NdVNOZ0hoOE1NU1llRCt4OWhlZWhnClIybldJNDFzekY2MEF1L3V0VE91
            eEN5SEw4L2NtaVJhamdkMkhYNVJwRm8KLS0tIHE5MkdUZCthSkliUTV4eHd5aXhY
            R1BGa1kwdjBRKzM3UjJBRXd0akJYTk0KlAwWaKUPesLw7RBoOEGpdWIa3+eH88Up
            TkWZy96NqC59PWkwwgSDptnDuPZWhCSGJDpxFSXMlZ7KgIthjfVlMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybzNCZzhxMWJPNWpjQnJP
            WThSSkROUXFzSzNZVjcvcTJnbmtyMVFrOVFzCm5icmlab2tzMHcwRTdSdTlmTEs4
            cmxpZGI1NllBYmRRcFRERFRGMGw0VmsKLS0tIGI5UHFmZG1rWWtQb2w1R0ROWi8z
            alhaRm5wNEVPOFRnNXQ4clJHT0pSUHMKUDVQ6Ag3dePKhbjE9lhfUF6Bb30vzeSl
            bRSEbjEsuU5PldqJCQpFqpdnsxajtMcl8/mMcsA0N6FvuyuvoGiOGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T04:35:30Z"
    mac: ENC[AES256_GCM,data:Ya7rkIXVKIFQSexFgCyK18/QDBsm6y8b5WuU4vsfcxc2l/LwUywJxLcfXr/UfZD1auM++2CWIAZdnji91iik0ZsiNOISI5D5oSjHBaRlHVHhBqo9xxTRVRzH0n0jb0CfHX45HiW+kVDGwoKTQV/k+HgXp1pMoUoYmGcSvU85Eu4=,iv:qh0brR3skzxoZlNvvwby7LvmWbucmS/LbhElihiya2Y=,tag:hUIh8oYsJCgHQTRsyDbOCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
