apiVersion: v1
kind: Secret
metadata:
    name: seaweed-admin
    namespace: seaweedfs
type: Opaque
stringData:
    WEED_ADMIN_USER: ENC[AES256_GCM,data:6xlKpHs=,iv:Dwj+mqhSlmzsHDzowdTfOh0b51H8k0LjoGIK5kucWeM=,tag:DO7T5RBdo0ty7nI1p/Yd3g==,type:str]
    WEED_ADMIN_PASSWORD: ENC[AES256_GCM,data:nXv9WbQpVSVwR3hM1NVkdkHG5FkMIcM2ziFH5TSaKENcKbELocDpBjPZ0243TpOEbdOCzfx6JYCoTVk+PSyD65WpsF8Vk7w3JKlDG5DdjARClOBkeRBHhA7yR9iB/6qF76G+KzsdwYO5a7KPs/Xz6dUux+01cZPAfp6lluOidjA=,iv:WNz13r+yfkD/W4PbGhZ1HJsAm/hxnDUFEIrh/2Ff0as=,tag:goncrGvSl5lwaRxsIr0t0Q==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQjFpZHRneXBFalpSUXRC
            Z1ptclNXajQyem1xVDZGdVhhMFdJbVpucFFZCkRWK2JQYlI0TGxWK2k5ZUplZEhC
            WXVCNDdzZjRiaXBjOFhPVXVldHF6NjQKLS0tIDZxOHBrVm9lT1ZpQlZXQ0k1NG82
            ZktvVTJpUnQ1UVJUYWtObm9iYzFFQlkKyDLBDx4detamGCkIGnoRn5ixK0RZcGhG
            FnXzDPZbtpb0sEZRtJaziqE+Z73JSd00/TH7JyHJYoATJByxt+eycg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRXdtWEJQOGoyREdyRXlR
            Sm91SENHNTJEYnhOdVRjMzlPd3NVRW9lWjBFCks3clkvem1rTDZZM3BONFNuR0FR
            SGFoVGsvQ0ZRSUR6cVZoZnFxNFZpUWcKLS0tIDdocjR0b0RndWpkMVM0RVZ0MTJF
            MlpYQWY4UXNFRmZVQW9rMzlRRmtIWWMKHUSKBuCB/fv/eXNa7aCZqDoOUs+VrFut
            BGfKPZJDCCFhlG9y8pmP5WA1g570EBeQ06lzAhuYFIFg37oSu9zH0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T02:39:33Z"
    mac: ENC[AES256_GCM,data:6dSUdCfsPRH/Zm3h/Fw9Nx0DfvkrXIaDn89JSxmIpU97hbW2830XNHGDZj2esXNkouB898rK+WwSNOyxjuX/2FEFN7PS0JVCPHvbvASueiCFl82GdQoXykmGtGIie7VSyO0DQ/6FSVjC/ejF0NblF8nmYPYt8f3m9B+xiNXPYig=,iv:cP7I84k4XI/73T13OPlTYOgVbroYkI7txgC1TtYVO0U=,tag:RD5U95N76renmCdeMLg7wA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
