apiVersion: v1
kind: Secret
metadata:
    name: spoolman
    namespace: printer
type: Opaque
stringData:
    database.username: ENC[AES256_GCM,data:0oQZ22d2dNY=,iv:8b5ZDCNSUFK+6fWxzLTHx7XYVpfhyCLkCyVnlHCOess=,tag:wEnEy77ntGbKCGaNn6k1HA==,type:str]
    database.password: ENC[AES256_GCM,data:XmngAeNSl+HgHr6ByNwN/2qXasTFVtdAl/axho1TlB0UIwxEMeGft31nxi7ro/rsCGS6+7I167k7jSpqc/weHnvG8QSUO0U06vwF4ThB45cs00QBINggvF+1TgQYVe/vYe2kWKRkmh1WOFarLxWqfouD2PAuwY/318CTiFgRTew=,iv:lFan12QQz5pH5RC2iTGB2CsqDCAQkSfreoWZWGePsKE=,tag:yYuZDAXVsQyFQTJkNHnDnA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRGdzUCsvYy9qdHJvVkFW
            bXBHVGhpNklpOHovTjc5RGFQdTdtODk5UUE4CmdiSGxJOEY4U3JmdndOOTlTckpX
            MHZmMlJ1R2d2MTRTTDBOYlVLZ1lNQUEKLS0tIG1rOXhYZHZxL0gyMDFPZzRJYlVs
            dGJQbWNwOWluQnJQd0NZL081SVN0d0EKx7xcI34V+Ex4UmndXW//RumWRTMg+lAO
            JC4q5YK9rRO1KpwtKvdyUKI+/CKZSNmMgoQUhcc5fphFbSIbLivCPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS2U2RzlUK0swcVRzdEZl
            dUlXd2d3RHU2QTgwKzZwd0pWQ25JTXRydzFnCjlZbGp0Z0NDUS8wOWttTVVQejFV
            bnNvVGFYVzhwVldyWUhqenEwZXpzT0kKLS0tIDV1alVOTysyQ09pbjgyUzFnaFpr
            T3h6V0d3VldiVSsxWlE4bm5KTU0wRncKyQOIVK8rO+CA9u5dCJwph5eODiApbHPx
            GWXFiz2a3KCwxkxbDz1b9smWkNpmNwM7C0S7If5VDqzxr+QxqSlA7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:26:38Z"
    mac: ENC[AES256_GCM,data:6VigpWjYQioUR7Eb/+NRcKii2dhWE0n81yayC5yCRXXutE2VI3bWB8RrdplRcPX/KOL3HzihYBHVHuTmgHNhG2gjWx9mZ5+ZU9qsnVrwbnWOrlthErKPDS7fP/EsIQrk8ctxsAk4OdPxYUPFobqr6nnlF/GFFPLdrMTxiSQcmsQ=,iv:s2mYzzlkMp9ULqxq7dhe4Hn9fj1HpLfA6TAYuuntZG8=,tag:rOSM+04WHuFN9RbDdqS3Iw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
