apiVersion: v1
kind: Secret
metadata:
    name: curseforge-api-token
    namespace: minecraft
type: Opaque
stringData:
    cf-api-key: ENC[AES256_GCM,data:CU4c5/vqFe/09HcFeSDlPeo/Z6afVRUHOuFI+Ln6AAskd5CMpPPT181jklKtoieO3A8uq5EG9pBob5G+u+g8,iv:ss/0mmAw4/aCXt2nnmbPYLDOcq1FrUmHq4oJ/8WS3z0=,tag:g4RliFK9vCi7aMuBwR3sPg==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYTNneGtKUit1b2tYQ2sx
            aHFOMFhGVzRqM0dEdUVnUk1HdUhRTmFJRUNnCmU0U0cybFNqRk8vVjFTWVAwa2N0
            K3lMQzlKUkZJTW1aTHduR210MlkyeUkKLS0tIHQ2aGZpdCtrbmtDVTNZTzRWcjdJ
            NDJyRDBRb29BMFN0VG81QlRJb2NseTgK+3OwNXfeMb8yghfABCW7vnyv3i/TZYW1
            uHVFB1tqf5ew8/6IZyPoN35iqj/CAsN4Cn0k/PLsvSHkBM4onW7IKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUTE1NnVWT3RzeDNTU3Bz
            VU9GMzFJSERzOUZLZHFoREd2THNuMlNvM0djCkhnWDQyaUxubkI3WXdVYXdRRVNs
            ZmZZWENDS0FnUFJmbklaNjQ1WGJRbXcKLS0tIEkwZFVFQkFHckZDaERJYzZNUTRQ
            YTdYd3ROclFZZ1hYblYzOXJtT1BhVjAK7rJBxqgwTD3ZTTLJdWIY2fI8L3ZY1V5M
            4T/xrU25QBvia0zsuJJYPIEh+RpjX8sGeyUqM3GbiI2xtslEBOFzMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T03:55:40Z"
    mac: ENC[AES256_GCM,data:LwTGtNVXiLPIoM5LZF9lUFmHpFafdrYI5jG5YLPnF8cAYKUMJ4zXXfFk9glnrPMTgas3VJ+ap3X03IVfkUl3+Esmo+30RoR0zlKUJhdZhK8Zlbh/73zM/hUFtvzCH6HeEZ3+VgOopDsZos9x1aDYrlso52MGbqZ1XSgnx3PSuiQ=,iv:FkmogVW5JOW51R8JqMnvgDs8N0UH9/CNdugQYcX9fXY=,tag:VcJlE+/D9qw+05QErKLMjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
