apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - curseforge.secret.yaml
  - ../gooncraft-reborn/app.yaml
  - ../kaylaatm10lite/app.yaml
  - ../oneblock/app.yaml
  - ../router/app.yaml
  - ../sweatysummersack/app.yaml
  - ../terrafirmagreg-modern/app.yaml