apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    apiToken: ENC[AES256_GCM,data:P8DPiq7PhNwnrSVUD3XM+UbIJ5ttmjyX5RqcVzfbo7DmXPJKV9jMZA==,iv:FWsIDPgkOKwx/44B7ZdIiSTA9ojKsYCCEdfuiMK61Hw=,tag:wAdy6qXW0GOzj+z7/+/S0A==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZnd0d0F5bkFQdnlSdllu
            bEtRMzZEU3Z2d0pMaWpNcThPamhHSVVzWjFVCit6TFNpNWcvTVdueE8wVzd6UVBK
            WmdodzRtcllmdHFnMHNOTWtMS21NclUKLS0tIG0zNkpzQVFTQUc4K1NLY2wzVkN0
            bE1QOTFhK0dxc1JId280YXNmQWZEQXcKWywIpwQGlulMScZH++pvRExTrGEKciSs
            GvsiqBG1yBhDA0V9/Glz+DzdFt+lmy/h4KMyR7ZF8rWDvMcT0G4tKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeHVKMjNGQ1pCMlNITnZw
            eEtwK3FGbmEwT0ZKOTltbE1zV1phWGJPcWlzCmdYbm5vRVFLQlNqTzdzOTE5MFQx
            QmUwbU1rQWNqZ3Vvd1RlWGlxMll6eTAKLS0tIEU4N3FkR2I4eHVoTEhUOHNYNWJY
            Y3I2cGVMeVhpZHQxTU1OUk93VmNLbGcK7k7gGbYxaJvoCSfEx8g1nT3s1bvawhma
            eQKLPYc8NjxSZFyWyl/ZO/atTGbQPtLhfkiwd8dwsLlvPXdR7p0Zcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T16:57:58Z"
    mac: ENC[AES256_GCM,data:BoMvB7u3MhSqXLLWA00qemvc6Vz2QyA7Ms3wqsIk/eNBG3raENTK1vbgn6qzkxtI30qJONRKR7MeJ28CCD+RImmeAlkprrynASclW2uTMJp8gpiDwBNI0kWRtzzbnSCx+v/UMnefbcMw5OmksevmZEZLlCu/N4ufz6KnXkflAaY=,iv:BKeWaQoeFpAVHKNgEKVfNv/2zw2AsVOyz329qlLplgo=,tag:jJXB6J8KI7qQ7sEoldOZHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
