apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cloudflare
type: Opaque
stringData:
    apiToken: ENC[AES256_GCM,data:P8DPiq7PhNwnrSVUD3XM+UbIJ5ttmjyX5RqcVzfbo7DmXPJKV9jMZA==,iv:FWsIDPgkOKwx/44B7ZdIiSTA9ojKsYCCEdfuiMK61Hw=,tag:wAdy6qXW0GOzj+z7/+/S0A==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZnd0d0F5bkFQdnlSdllu
            bEtRMzZEU3Z2d0pMaWpNcThPamhHSVVzWjFVCit6TFNpNWcvTVdueE8wVzd6UVBK
            WmdodzRtcllmdHFnMHNOTWtMS21NclUKLS0tIG0zNkpzQVFTQUc4K1NLY2wzVkN0
            bE1QOTFhK0dxc1JId280YXNmQWZEQXcKWywIpwQGlulMScZH++pvRExTrGEKciSs
            GvsiqBG1yBhDA0V9/Glz+DzdFt+lmy/h4KMyR7ZF8rWDvMcT0G4tKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeHVKMjNGQ1pCMlNITnZw
            eEtwK3FGbmEwT0ZKOTltbE1zV1phWGJPcWlzCmdYbm5vRVFLQlNqTzdzOTE5MFQx
            QmUwbU1rQWNqZ3Vvd1RlWGlxMll6eTAKLS0tIEU4N3FkR2I4eHVoTEhUOHNYNWJY
            Y3I2cGVMeVhpZHQxTU1OUk93VmNLbGcK7k7gGbYxaJvoCSfEx8g1nT3s1bvawhma
            eQKLPYc8NjxSZFyWyl/ZO/atTGbQPtLhfkiwd8dwsLlvPXdR7p0Zcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T17:08:20Z"
    mac: ENC[AES256_GCM,data:5c1T94tIRmycjD76yE/i2P7hHME/CsXsMAnoqeYM/mDeoNahh9smm3TqioTtzfLBGw0+ElW85knEtyGygKVXZv/DxKXsZIFB9t4eMHEom/kMHM8xvOti8iJLE8HYUGTkxKkKjHQ3jUAyc0iJieImyBf9C5lAst3PKgXUUGskhUc=,iv:sZYnHcWuOctc5l4WQR597z7qYmNRlJfQi6Wj0SH1RTo=,tag:9BMWvkTkrJv/wpoLzqm/PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
