apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  endpoints:
    - dnsName: alerts.saturn.ci
      recordType: CNAME
      targets:
        - direct.saturn.ci
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: prometheus
  namespace: monitoring
spec:
  endpoints:
    - dnsName: prometheus.saturn.ci
      recordType: CNAME
      targets:
        - direct.saturn.ci
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
# ---
# apiVersion: externaldns.k8s.io/v1alpha1
# kind: DNSEndpoint
# metadata:
#   name: thanos
#   namespace: monitoring
# spec:
#   endpoints:
#     - dnsName: thanos.saturn.ci
#       recordType: CNAME
#       targets:
#         - direct.saturn.ci
#       providerSpecific:
#         - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
#           value: "true"