apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-helm
  namespace: argocd
spec:
  project: default

  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.16.1
    helm:
      releaseName: metallb

  destination:
    name: in-cluster
    namespace: metallb-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
    automated:
      prune: true
      selfHeal: true

  