apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: printer-spoolman
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baconing/dots.git
    targetRevision: argocd
    path: kubernetes/home/printer/spoolman

  destination:
    server: in-cluster
    namespace: printer

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true

  plugin: {}