apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: slskd
  namespace: media
spec:
  secretName: slskd.saturn.ci
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - slskd.saturn.ci