apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-alert-manager
  namespace: monitoring
spec:
  secretName: alerts.saturn.ci
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - alerts.saturn.ci
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus
  namespace: monitoring
spec:
  secretName: prometheus.saturn.ci
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - prometheus.saturn.ci
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: prometheus-thanos
#   namespace: monitoring
# spec:
#   secretName: thanos.saturn.ci
#   issuerRef:
#     name: letsencrypt
#     kind: ClusterIssuer
#   dnsNames:
#     - thanos.saturn.ci