apiVersion: v1
kind: Secret
metadata:
    name: curseforge-api-token
    namespace: minecraft
type: Opaque
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:TkD5U+6Zx0PO6OG6pYSiu72tPAcv6dPsQoAXNMKQ7fQS36CVVZ98SEDE57vYlX/ltYjvDvwvVD6YV2u3,iv:rItkiuLerk0x4MNkuTsIMavq3+59/Tfj4bTgBT7N5e8=,tag:BHehpFUpojq/iDpfis7Rgg==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYTNneGtKUit1b2tYQ2sx
            aHFOMFhGVzRqM0dEdUVnUk1HdUhRTmFJRUNnCmU0U0cybFNqRk8vVjFTWVAwa2N0
            K3lMQzlKUkZJTW1aTHduR210MlkyeUkKLS0tIHQ2aGZpdCtrbmtDVTNZTzRWcjdJ
            NDJyRDBRb29BMFN0VG81QlRJb2NseTgK+3OwNXfeMb8yghfABCW7vnyv3i/TZYW1
            uHVFB1tqf5ew8/6IZyPoN35iqj/CAsN4Cn0k/PLsvSHkBM4onW7IKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUTE1NnVWT3RzeDNTU3Bz
            VU9GMzFJSERzOUZLZHFoREd2THNuMlNvM0djCkhnWDQyaUxubkI3WXdVYXdRRVNs
            ZmZZWENDS0FnUFJmbklaNjQ1WGJRbXcKLS0tIEkwZFVFQkFHckZDaERJYzZNUTRQ
            YTdYd3ROclFZZ1hYblYzOXJtT1BhVjAK7rJBxqgwTD3ZTTLJdWIY2fI8L3ZY1V5M
            4T/xrU25QBvia0zsuJJYPIEh+RpjX8sGeyUqM3GbiI2xtslEBOFzMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T03:45:23Z"
    mac: ENC[AES256_GCM,data:w3x51nrg/sSFEYhGa8tWNc7lPZ4GOt4bi87Ls2x8iF5PY/CexkewSilWEVoTErmDkWFT8cv2scgyFUQn2nNtsAU6TJKTW/PCCJ8RajdBe6LGkcrMqb4xAh/bV4p811n97ujo0dzKNlyBGPe575Pq893f/aI/bHjr9NHwN7mgkxQ=,iv:ojNm2yG1Fo388kq8KKdJfcSGlIQl0tMe608IcrI1cQQ=,tag:qN6MPEhqW8xfC2nn0W/B4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
