apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-seed
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cross-seed
  template:
    metadata:
      labels:
        app: cross-seed
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: cross-seed
          image: ghcr.io/cross-seed/cross-seed:6.13.6
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          command: 
            - "/usr/bin/catatonit"
            - "--"
            - "/usr/local/bin/cross-seed"
            - daemon
          ports:
            - containerPort: 2468
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /config/config.js
              name: config-file
              subPath: config.js
              readOnly: true
            - mountPath: /downloads
              name: downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: cross-seed-config
        - name: config-file
          configMap:
            name: cross-seed-config
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads