apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-creds
    namespace: database
type: Opaque
stringData:
    defaultEmail: ENC[AES256_GCM,data:y8EP7vlRwRghCjhipzMZ,iv:X2sEQ11QqwMrQmU3u/P/tRrMbaWLqK/cBbWKVcH+5vg=,tag:3/DptlbonABXD4gkjwvT+Q==,type:str]
    defaultPassword: ENC[AES256_GCM,data:qeyttrLgT9L8ezUAvd8R56ZOiszL8GZIrl35kfEMe65/U10CjL17o2MOgbNdMAXNXDBsvLIjKLRYxpC1oKfP5uBVgbJYv9LSU6TBl5H5Sy6u8z02Ag+hLiINlHBNjOX2KNAsp/ym/wE9TVUIhC7UwKanz0objZG54Qjy3WKaALg=,iv:sbzjkih/3nwqowc87nkElETgVXCSGBG1yQls2eBHfzo=,tag:JcZVqHpiCszX4EBOjfacjA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYjFmRmpJd0xGZXdpQmVl
            ay9MSlRLVlg4bjVMQVlEVGIyRk0yUElJYlNRCmhmU2pCaitEa0FHQi9ldWZnNTVa
            KzIzZnBndURYTnlYY3RoVWVKTmFrMmcKLS0tIGFFTk5VU0VJUGdvelJBQkZpR0tE
            YU13ZGlIRFRoL0JlZXJ3SkhTMVlSMjQKus8P7KzlFS4CJmhnA1E8zyDF7oOOx2FU
            /M3c88MXoRq43Njtu22+H3kzx7FpieuqKRm9R6Fsos+drsiCxfpD/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZWx0SkVUSEZaNnpmdDB0
            VmNzTnRXaERUY0doNkNYK3VhMUJweG9IS0FzCm5tZWIrNEluVlA2eDh6aXI5NGQr
            WXE1MWg5aWdkMWYwYWJVNXUvdVppZ3MKLS0tIDA0ZGZ3Q3FtVXZzemlVRGdtNDU4
            YkVPbWdxQkNJRnA0akVjM2tQZkxUR1EKV4Uk1GPJSv5Fv3Dkzj5Tg6ixGIDpJQYv
            wuLLuUbLLW5cTgGQBWpPYS4bIvY0LIpbXL7lvPfa4qYd+3dXRWC3Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T14:46:32Z"
    mac: ENC[AES256_GCM,data:sWWSJn7KFeeLXaeKT+cTgEEz+w2t7GyneFwlFT30KPyMQOct+Yud3JfmJs1ncKUSOsu0VgO2bLD9Zpl6vdjIlZTawcMEEhdUbIgY0SvyvfINUoyzx8tuGzVDVF69T0Q52NCZpCOunnGcZuOlbAkmcpuw2ODrdRV28X7HsnzAIlI=,iv:4ZEpt6kqkgTqQ6I9NmI2Y5WqaGMgVIQHOm0QT/2ZMjM=,tag:fGORSFWjW/gHJ/pTpK+UqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
