apiVersion: v1
kind: Secret
metadata:
    name: pgadmin
    namespace: database
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:flKkGiollSL3aHSswtxl,iv:gB+EcSZwN2VYJ9KPiIfL7k6+nxNtSHCPW/b33oNdY6Y=,tag:WXOtXvPtVCAU/fB7NPMgcw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:CGL/vG+m/9c4rZY92B4iGcrhDfhOwk90dmLynNbr07FcIUIEjxGleUUiF3+mR6TpvGj/8Y44llHbLyZazpFIaiYRtYaYl+OVDmPzPguM5/gdUBN8OwAfyF1ZJhBFd8aZYA/D0VB2CVm8Kh8rkRM29mk0AOBBuRgc0Vtgn9GdtG8=,iv:7h6n4QoD9sbVPugzt5fzSDbnhAGyFGLKlZYn1PyIXA0=,tag:S87NJkwKIl/gb8+upRb9ng==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYjFmRmpJd0xGZXdpQmVl
            ay9MSlRLVlg4bjVMQVlEVGIyRk0yUElJYlNRCmhmU2pCaitEa0FHQi9ldWZnNTVa
            KzIzZnBndURYTnlYY3RoVWVKTmFrMmcKLS0tIGFFTk5VU0VJUGdvelJBQkZpR0tE
            YU13ZGlIRFRoL0JlZXJ3SkhTMVlSMjQKus8P7KzlFS4CJmhnA1E8zyDF7oOOx2FU
            /M3c88MXoRq43Njtu22+H3kzx7FpieuqKRm9R6Fsos+drsiCxfpD/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZWx0SkVUSEZaNnpmdDB0
            VmNzTnRXaERUY0doNkNYK3VhMUJweG9IS0FzCm5tZWIrNEluVlA2eDh6aXI5NGQr
            WXE1MWg5aWdkMWYwYWJVNXUvdVppZ3MKLS0tIDA0ZGZ3Q3FtVXZzemlVRGdtNDU4
            YkVPbWdxQkNJRnA0akVjM2tQZkxUR1EKV4Uk1GPJSv5Fv3Dkzj5Tg6ixGIDpJQYv
            wuLLuUbLLW5cTgGQBWpPYS4bIvY0LIpbXL7lvPfa4qYd+3dXRWC3Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T03:47:07Z"
    mac: ENC[AES256_GCM,data:O0xdcAJmZLGL+7fZgF0SajLxJ2/1MNCWrv1teKUPW0LdD2Wc1huJyBv9BlqaRce2Pg7dCZw6nDveg49xX+VA4pEfDCDV57JwqLUwL93RMIy8OlgGmuhE0gX9lVpkQIcTSsuo4YYzrrDyU8m2mrk9+lGpmS4TlUGliSOwiSEirhs=,iv:X42BYHKJerB8qEBHkc2VaOupZ02vpc/IcgZvKAZe1lk=,tag:edwMnDhlkrYyvMb8KS73HA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
