apiVersion: v1
kind: Secret
metadata:
    name: lldap
    namespace: auth
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:/nQsQWe8n5nj7stWqNZ7aojQ6N1QGv8cQYVu3HGcBalSxjzgRAnLzuD2i+GSpG5tzFLb5szoCM8VN5Pd/3qgnry6zQPSnUJlmLCer5PKZS6KYQdYkpRTzn8bHLR4y6o36n7EIkfuOoOYJExH0EHHqAt2EhZzHuKHsDkVn5zC61pus9ObazchVWcSGPtDAyYB5fcNUIrgx1kNU90f3epNYePyqDyZCY7D6ho5a+nqbW/zh9fUoW++XTtx4tBo/HUqW/xyOavka8vpubnTGpEL93OY/yBqXGnvqdv2VVzKriGR2/u4pnW8Q8pbjz7C2aY4XmSlN8sSwUhY3LILTdD6a8+uH1/bQ2SfhvXy/Zcdk+gYh16h+gzRD/245TnZUwqIf35Ie0KP4TdocVWOribukxc/7R98Ne5KrCbPAh2uLh6pMU+VQBZo7khjtgi7pQaA43W98RS28OyDfTEzi5zdgMZHmpMeOmEIDUzff9rjbP6S9gcJMcy0H/4MlHLgLVUcvnfNFx5rX3GmPP2ZHjx5Yh3C3pkS84H3SuXyudfj6czFaVhU2q/zrSkghvpUUPb7GEW/agiuc3VjxjSyIUBBbwvUbB6Pbg/2/FVa82JJ3PovR3gc0MWiEFGLwpN1cgbzRVV0ly0Pps/sV/GK4wSH4nlqc0J+,iv:joKXAcfiIOj07rSZbjaF0pmuecexJV0xUxLguLB18cQ=,tag:4nuhzUa3QZCi/mz4i5dcYA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN1pmNHc5NDI2K1REQktr
            WWNoaGtHVW5FZ01TdWVzSVJTa1NmUFljSEZZCnU3cU1iY2QyTFl4Y1BDMmZQdGV2
            bWJ1K0RONDl0R0FKZFMxZFM4RVg2ODQKLS0tIHZ6dVk3eHZuK0tSY01EbURoMllv
            RUx5NjNJMFhCdTNmcXA1Qk81Vk9yQkUKLUUz0AhzKxwqTer5CmgnWICKK7vJ8WtB
            m6tVQP0jd/wW5trD8kZsu4S3rzbpU9JKsLSfbAbkndDVg8Jtoq9H+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSTNHSC9hcklxUS9xdk10
            VFV5R3pVTWgwWE1Sbk5Od0ZFUkZKSWZsVENzCmpMYmQyQW5NdnU1NTdxUkNCUlpM
            YVpiWis5Q202ci9ONkNackN5SWdQOVUKLS0tIEp4UTRhc0tZQzRlb282dDM1Rlc3
            Si90N29qdnNEUk1OeDVPQkZBdmJWSUEKxWYe+P5E3gbJyeSjHsyU7XtefITM10Si
            tE3Rsu1BqvGWrfA8P3eIqSiSwXfTZKy/VW3Y4mzovP4bMH5iTs52fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T01:05:18Z"
    mac: ENC[AES256_GCM,data:SLe/JGrI5xNZDNYYYiefeXlk7eeour4Psls+Y4eq+5ILnKh8vQMER0jHCqdYYAZPkPqVI0Xqkf/ic+YCw64OKL86ntouhUiA5A6qgNnZXZOR+wxItONTzuK33s5uT8FeGggPGDB8iA6uRUyR9+W33qHIwYtkjOWMl9ENGwvDhdU=,iv:NuhTlJ+3vPOqRsuSvWRCjLYLMQqBnv9qHTkI7zSW2jE=,tag:UFYHI7y2QpqJ8bksuWtEBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
