apiVersion: v1
kind: Secret
metadata:
    name: lldap
    namespace: auth
type: Opaque
stringData:
    secret.lldapJwtSecret: ENC[AES256_GCM,data:J2dxjVJiK/pn4I6FhLTuEBnB47YXJpBQCVqsqIF722jN5AaVJwYU8qrJbX8XtrHw90gZxCr64WS18JzUHx8px3TD8A86688A0Jhs+WGkS0sjolcCY1unoB+p4EWD3cqYY9ZsrR++WVYGUzJv83E4L7BnfeS4SnoDGf+3y5W32f4=,iv:yYTdgf8XAu//6jViOmGylfOgPHE/pvvBCDDPgUTxudI=,tag:ByUYNapfLq4q0YQbJdUhig==,type:str]
    secret.lldapKeySeed: ENC[AES256_GCM,data:mSTHfbnpO9q/fsgdz7ZhWBG98IaTqGBz59IA0SCqG0Tp4qougDDb4ZFwPpWjX7Wz58+m1GmCEHZFdwz+nFVv3vs7f6LDrKTwwwb6md7Jx6bgRWp1oDAxqObwiFP8D+Y1Cybe7ErGlr7n6QcEOvKwG/lyDGbKMLLmAYPQi+JYPrU=,iv:fJeYWcEH89B+CYHaFI+giZbhSr87S50ObRt+Q/DZhL0=,tag:ap/CdoOkCyFwRCWU9c6LzQ==,type:str]
    secret.lldapUserName: ENC[AES256_GCM,data:F4JXKb0=,iv:hiwM80JrZTn2+T2GhGkTu8Uq7qYHAh3z70EtCMrufo4=,tag:rFLVZiFaiB1j8l2YjhjLNA==,type:str]
    secret.lldapUserPass: ENC[AES256_GCM,data:xMd6yxy0NsFBMYoavLkkMkpYqLcBYcDDWR/OMASMJ27kyylzdohILKOqfV5v7LubTR1WsUNVHpkstS3BPXEhfwJCjy5k8YHrrFuFP2MMwMQzlB2+lJSuhTjAbAhtBWPv59dWonyv9h2XGAgxtg6f7MmH4PYIQfKSprWvF336Nr4=,iv:019HRNaILukiRvvSWcpSQaSQpazuFjHVPhQ9ippM3wQ=,tag:RUTprMB+GyG6awXB7ud4Tg==,type:str]
    secret.lldapBaseDn: ENC[AES256_GCM,data:HMZn4cu2n4/M2h/XNCZVKQ==,iv:rLWu6dQYFoqH8wkTMNluKqGmO465SXBsLDJbd8+2XNs=,tag:teSiKZcnWVNFIluS+peFrQ==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN1pmNHc5NDI2K1REQktr
            WWNoaGtHVW5FZ01TdWVzSVJTa1NmUFljSEZZCnU3cU1iY2QyTFl4Y1BDMmZQdGV2
            bWJ1K0RONDl0R0FKZFMxZFM4RVg2ODQKLS0tIHZ6dVk3eHZuK0tSY01EbURoMllv
            RUx5NjNJMFhCdTNmcXA1Qk81Vk9yQkUKLUUz0AhzKxwqTer5CmgnWICKK7vJ8WtB
            m6tVQP0jd/wW5trD8kZsu4S3rzbpU9JKsLSfbAbkndDVg8Jtoq9H+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSTNHSC9hcklxUS9xdk10
            VFV5R3pVTWgwWE1Sbk5Od0ZFUkZKSWZsVENzCmpMYmQyQW5NdnU1NTdxUkNCUlpM
            YVpiWis5Q202ci9ONkNackN5SWdQOVUKLS0tIEp4UTRhc0tZQzRlb282dDM1Rlc3
            Si90N29qdnNEUk1OeDVPQkZBdmJWSUEKxWYe+P5E3gbJyeSjHsyU7XtefITM10Si
            tE3Rsu1BqvGWrfA8P3eIqSiSwXfTZKy/VW3Y4mzovP4bMH5iTs52fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T00:23:58Z"
    mac: ENC[AES256_GCM,data:AQ+Guf5ujGtgWWTZu/nB6YLHKgjDewMbb2FhiS+nZQO+cyw8tDCiKRflG0vP2G+2p08l1NY0hMnIPDwR8fGHODsWDe19mZdynd2lbUDr8A3Gjk5HR0F5cZQhwL8J7vXMfPl3IkH1++MTx/+F54wSHSIKj5103INXrxipjWv9xlI=,iv:MPv6ClWAzLj1vvWCL+pCgkc7iiDjD8jMIdymS44Z5ys=,tag:MPtqKSKeG5krLe1goTj4Cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
