apiVersion: v1
kind: Secret
metadata:
    name: lldap
    namespace: auth
type: Opaque
stringData:
    jwtSecret: ENC[AES256_GCM,data:igLzIoSpY5ggEAua3WW1J6qt5ZII819F2XIbP+aB/aiepeE24XFg+rnn+Y7higqJmUNGc3eK2WlUBsWDoo9WbVUOYxLllgESpgfZGDMPPiF3kwgGsVsIczGAG7o540tUcCuOdkiGKisCt8hSR4uF3z+qu9Cuo43O8o1TJivZ6C0=,iv:FR6Www2a6q3GGaikJMgwyW0HGhfDvgOIfZIHh4ou0S0=,tag:Tsh+8SWGuXN4SZMV2koqKA==,type:str]
    keySeed: ENC[AES256_GCM,data:m+XnWnDgxoIdCghxmMsyz2S8/s/GOYgrb8ZYyMzVUALGWQ4SC4k2ircObEIkIg7UO7h4XagcPrpJWBv8989YTvrcWQGE22inEyMwWzgnTo9P++GjBV1zDxuIBU8y+nsHHmVD7+IKsjhIovRr4MJsz9Yn3O5CeXwUjERa7RivyB0=,iv:qBFB3OLt+h19nsmbAenrFBe6WuB3F5rckwdk6jX2JIE=,tag:TQUaZ3zw+5zA9dueLk8ODQ==,type:str]
    ldapUserPass: ENC[AES256_GCM,data:qNdruYS4l2x1E5wWoyGs50S9u5ivkh2qfMRHMeSzgX1cg+xUzXbHyrK0HpnzndtXgd7V6vcYZTo0a+wEJHR0oKWW6SGL+tr2ifhdWjxtV9jaFUHVCni+3m/i1p6B2wSeQQu1vLxKRpvSW2wBW0cDNVdbmMzrEffP/rdIbX3iZWE=,iv:sw6qrVMM4/43GQxta4/MQjcpXto5/nsd1Eala49cPzw=,tag:OzY/bgYDW4vURUdhBVBC0g==,type:str]
    externalPostgresql.auth.password: ENC[AES256_GCM,data:uECKhhlLcui6LOcHg/azhycMYyw4Gy3yXjtlRG0SAQy+J1dSDYii0QNNQwAwFH/OXfytawXIKYsYjRsKCW8K0fcHLUGpGmL9ciQuMaLTAXDpGcLl9Wu6adfumDNZchF1slYBJOKpP/QZlY5CFn/BZlVYgkwUVaLL2uWfn/wMIT4=,iv:hLS+piX3JGWRVDtdKPSP9IeCHwfQFYlewRBLDhEgE/g=,tag:lVRzj3+88veuOGkvxDDcaA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN1pmNHc5NDI2K1REQktr
            WWNoaGtHVW5FZ01TdWVzSVJTa1NmUFljSEZZCnU3cU1iY2QyTFl4Y1BDMmZQdGV2
            bWJ1K0RONDl0R0FKZFMxZFM4RVg2ODQKLS0tIHZ6dVk3eHZuK0tSY01EbURoMllv
            RUx5NjNJMFhCdTNmcXA1Qk81Vk9yQkUKLUUz0AhzKxwqTer5CmgnWICKK7vJ8WtB
            m6tVQP0jd/wW5trD8kZsu4S3rzbpU9JKsLSfbAbkndDVg8Jtoq9H+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSTNHSC9hcklxUS9xdk10
            VFV5R3pVTWgwWE1Sbk5Od0ZFUkZKSWZsVENzCmpMYmQyQW5NdnU1NTdxUkNCUlpM
            YVpiWis5Q202ci9ONkNackN5SWdQOVUKLS0tIEp4UTRhc0tZQzRlb282dDM1Rlc3
            Si90N29qdnNEUk1OeDVPQkZBdmJWSUEKxWYe+P5E3gbJyeSjHsyU7XtefITM10Si
            tE3Rsu1BqvGWrfA8P3eIqSiSwXfTZKy/VW3Y4mzovP4bMH5iTs52fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T04:12:54Z"
    mac: ENC[AES256_GCM,data:piEGeYhOqlIlaQwxsI8XYCiwSCnRu9vyhaEZYiTanTnNTDSw/SxnzZBA3QdrxGvpC0p3s1SDD/LxioeAIWRqSOh99E6XRgqTUGxQJpOCkY1CYm0afEwNuQLuRqvIYP3bdyTqh4NRPJ/S2uKeOgbdqum2ogB0i5vJqwSDo8zu7hs=,iv:/0sfBnR7FGOWTk/omrZ6kXdCPj27bO7wmN54QH/WTkA=,tag:JpfH3qtFg9mqbFDh4lK11w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: lldap
    # todo
    namespace: database
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:/zfNwpfHZVrjqk+Lbqr2evPaBHg7ws/X+a7KRkBXlkDXvS6IL2a3d7GwT7owhZ7h0nxad6Tl64B5b5PFkWm/SSMu06CL24+HJQM/5LO7tgq+3FjusVMEZW9NkjYRLEq+RLZVZH0VG5ICpGsmRi8Xqy7UsbGm3oEbV2Z12ELoTyg=,iv:TO6qveMlRPXcF8uyH3EYMHNDBcrjhkC+9bpjkS6VTLI=,tag:rsTe30UkkUAMlftAyi0AYA==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN1pmNHc5NDI2K1REQktr
            WWNoaGtHVW5FZ01TdWVzSVJTa1NmUFljSEZZCnU3cU1iY2QyTFl4Y1BDMmZQdGV2
            bWJ1K0RONDl0R0FKZFMxZFM4RVg2ODQKLS0tIHZ6dVk3eHZuK0tSY01EbURoMllv
            RUx5NjNJMFhCdTNmcXA1Qk81Vk9yQkUKLUUz0AhzKxwqTer5CmgnWICKK7vJ8WtB
            m6tVQP0jd/wW5trD8kZsu4S3rzbpU9JKsLSfbAbkndDVg8Jtoq9H+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSTNHSC9hcklxUS9xdk10
            VFV5R3pVTWgwWE1Sbk5Od0ZFUkZKSWZsVENzCmpMYmQyQW5NdnU1NTdxUkNCUlpM
            YVpiWis5Q202ci9ONkNackN5SWdQOVUKLS0tIEp4UTRhc0tZQzRlb282dDM1Rlc3
            Si90N29qdnNEUk1OeDVPQkZBdmJWSUEKxWYe+P5E3gbJyeSjHsyU7XtefITM10Si
            tE3Rsu1BqvGWrfA8P3eIqSiSwXfTZKy/VW3Y4mzovP4bMH5iTs52fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T04:12:54Z"
    mac: ENC[AES256_GCM,data:piEGeYhOqlIlaQwxsI8XYCiwSCnRu9vyhaEZYiTanTnNTDSw/SxnzZBA3QdrxGvpC0p3s1SDD/LxioeAIWRqSOh99E6XRgqTUGxQJpOCkY1CYm0afEwNuQLuRqvIYP3bdyTqh4NRPJ/S2uKeOgbdqum2ogB0i5vJqwSDo8zu7hs=,iv:/0sfBnR7FGOWTk/omrZ6kXdCPj27bO7wmN54QH/WTkA=,tag:JpfH3qtFg9mqbFDh4lK11w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
