apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap
  namespace: auth
spec:
  secretName: lldap.saturn.ong-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - lldap.saturn.ong