apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-helm
  namespace: argocd
spec:
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.16.1

  destination:
    server: in-cluster
    namespace: metallb-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true