[bar/main]
monitor = ${env:MONITOR:}


font-0 = "3270Medium Nerd Font:pixelsize=12;0"

fixed-center = true

module-margin = 1

modules-left = i3
;tray-position = ${env:TRAY:}
modules-right = xkeyboard battery cpu memory temperature network pulseaudio date

; planned modules:
; backlight
; battery
; date
; memory
; mpd (potentially)
; network
; pulseaudio
; temperature

[module/i3]
type = internal/i3

pin-workspaces = true
show-urgent = true

strip-wsnumbers = true
index-sort = true

enable-click = true
enable-scroll = false

fuzzy-match = true

[module/xkeyboard]
type = internal/xkeyboard
format = <label-indicator>
format-foreground = #ff0000

label-indicator-on-capslock = בּ
label-indicator-on-numlock = 
label-indicator-on-scrolllock = 

[module/battery]
type = internal/battery

full-at = 99
low-at = 15

format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>
format-low = <animation-low> <label-low>

label-charging = Charging %percentage%% (%time% until full)
label-discharging = On Battery %percentage%% \ %consumption% W
label-full = Battery Full %percentage%%
label-low = On Battery (Low) %percentage%% (%time% until drained)

animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

format-low-foreground = #ff0000

[module/cpu]
type = internal/cpu
interval = 0.5

format = <label>
format-prefix = ﬙

label = " %percentage%%"

[module/memory]
type = internal/memory
interval = .5

format = <label>
format-prefix = 

label = " %used%/%total%"
