apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.12.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      reclaimPolicy: Retain
      defaultDataLocality: best-effort
    
    defaultSettings:
      backupTarget: "cifs://10.10.2.2/kubernetes-backup/longhorn"
      backupTargetCredentialSecret: longhorn-nas
      replicaAutoBalance: best-effort
      defaultDataLocality: best-effort
      
    metrics:
      serviceMonitor:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s

    ingress:
      enabled: true
      ingressClassName: traefik
      tls: true
      tlsSecret: longhorn.saturn.ci
      secureBackends: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Longhorn
        gethomepage.dev/group: Storage
        gethomepage.dev/icon: longhorn
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: 'traefik-forwardauth-authelia@kubernetescrd'
        external-dns.alpha.kubernetes.io/enabled: "true"
        external-dns.alpha.kubernetes.io/hostname: longhorn.saturn.ci
        external-dns.alpha.kubernetes.io/target: direct.saturn.ci