apiVersion: v1
kind: Secret
metadata:
    name: longhorn-nas
    namespace: longhorn-system
type: Opaque
stringData:
    CIFS_USERNAME: ENC[AES256_GCM,data:lJ0ygJ/2udHtCRM=,iv:jRECNyD54kqyHCsbaw6fupW80DSQZ+yrOPrzLLGXc20=,tag:gSt0oOCzOQLW4gJwkWGfFA==,type:str]
    CIFS_PASSWORD: ENC[AES256_GCM,data:pO3kYtjUwlY+Th0zIw71HaXxkx0=,iv:SHJcnM+ljwUR6ri4dxlwqkX1XXfzXe4bZWVPzwENgvw=,tag:evIor9EPMU+zNXi18W9pzw==,type:str]
sops:
    age:
        - recipient: age1m3lajqjssue8jnuuhphxp3x0lxagksqpsecgnuxuy46wtag28c5spm5jyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQjFpZHRneXBFalpSUXRC
            Z1ptclNXajQyem1xVDZGdVhhMFdJbVpucFFZCkRWK2JQYlI0TGxWK2k5ZUplZEhC
            WXVCNDdzZjRiaXBjOFhPVXVldHF6NjQKLS0tIDZxOHBrVm9lT1ZpQlZXQ0k1NG82
            ZktvVTJpUnQ1UVJUYWtObm9iYzFFQlkKyDLBDx4detamGCkIGnoRn5ixK0RZcGhG
            FnXzDPZbtpb0sEZRtJaziqE+Z73JSd00/TH7JyHJYoATJByxt+eycg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17v6mkt3sh9h5j90pgaehrhu0ntdvksh8dw0lc69y3hp508lxxycsd5dynl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRXdtWEJQOGoyREdyRXlR
            Sm91SENHNTJEYnhOdVRjMzlPd3NVRW9lWjBFCks3clkvem1rTDZZM3BONFNuR0FR
            SGFoVGsvQ0ZRSUR6cVZoZnFxNFZpUWcKLS0tIDdocjR0b0RndWpkMVM0RVZ0MTJF
            MlpYQWY4UXNFRmZVQW9rMzlRRmtIWWMKHUSKBuCB/fv/eXNa7aCZqDoOUs+VrFut
            BGfKPZJDCCFhlG9y8pmP5WA1g570EBeQ06lzAhuYFIFg37oSu9zH0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T00:37:31Z"
    mac: ENC[AES256_GCM,data:V2u3dChybg0FEVSOn60vgG9oCzhxMg77b3J4IUUSJ1+RSmvAH2EmzMIefvybRVIj5d0/IoWH/0WYVdRRGW3r7vv//JD/EAUiuqOsd8iGXxEkbw9v8Xy2ha3pEN1xU/D9LO2ri0Pur/EbLmMzAVdZ9wbJGkukuSsBdQAZFCaQYyQ=,iv:SY3tU/KhBTtDHsSFj1JIzBC1r1Rj8BSPQArueQbBX5Q=,tag:qg5frUQabVtVXS/7uKptDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
