apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-sweatysummersack-helm
  namespace: argocd
spec:
  project: default

  source:
    chart: minecraft
    repoURL: https://itzg.github.io/minecraft-server-charts/
    targetRevision: 5.1.3
    helm:
      valuesObject:
        image:
          repository: itzg/minecraft-server
          tag: 2026.7.0-java21-jdk
          pullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 1
            memory: 8096Mi
          limits:
            cpu: 4
            memory: 16384Mi

        extraEnv:
          INIT_MEMORY: 8096M
          MAX_MEMORY: 16384M

        envFrom:
          - secretRef:
              name: curseforge-api-token

        livenessProbe:
          initialDelaySeconds: 300 # 5 minutes

        workloadAsStatefulSet: true
        strategyType: OnDelete

        minecraftServer:
          eula: "TRUE"
          type: AUTO_CURSEFORGE
          difficulty: easy
          whitelist: "Baconing,TickleKnees"
          ops: "Baconing"
          enableCommandBlock: true
          spawnProtection: -1
          viewDistance: 32

          motd: "i love you so os sososo so soso so sos o much meow"

          autoCurseForge:
            apiKey:
              existingSecret: curseforge-api-token
            slug: all-the-mods-10-lite
            fileId: "7420356"
            includeMods:
              - living-things

        persistence:
          storageClass: longhorn
          dataDir:
            enabled: true
            Size: 16Gi
            accessModes:
              - ReadWriteOnce

        serviceAnnotations:
          mc-router.itzg.me/externalServerName: kaylaatm10lite.saturn.ci,kaylaatm10lite.local
          external-dns.alpha.kubernetes.io/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: kaylaatm10lite.saturn.ci
          external-dns.alpha.kubernetes.io/target: direct.saturn.ci
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"

  destination:
    server: in-cluster
    namespace: minecraft

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true

  plugin: {}