name: Renovate
on:
  schedule:
    # Run every 30 minutes:
    - cron: '0,30 * * * *'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: renovatebot/github-action@v46.1.17
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 43.251.3